"""
Automotive Diagnostic Trouble Code (DTC) database.

Maps OBD-II / SAE J2012 generic trouble codes to their standard official
short descriptions. Covers:
  - P0xxx generic powertrain codes (fuel/air, ignition, emissions, speed,
    computer, transmission, and the P0Axx hybrid range)
  - C0xxx generic chassis codes
  - B0xxx generic body codes
  - U0xxx generic network/communication codes

Only standardized generic codes are included. Manufacturer-specific
(P1xxx / C1xxx / B1xxx / U1xxx and similar) codes are intentionally omitted
because their meaning varies by make.

Usage:
    from dtc_database import DTC_DB
    desc = DTC_DB.get("P0301", "Unknown code")
"""

DTC_DB = {
    # ---- P00xx: Fuel and Air Metering and Auxiliary Emission Controls ----
    "P0000": "No Fault",
    "P0001": "Fuel Volume Regulator Control Circuit/Open",
    "P0002": "Fuel Volume Regulator Control Circuit Range/Performance",
    "P0003": "Fuel Volume Regulator Control Circuit Low",
    "P0004": "Fuel Volume Regulator Control Circuit High",
    "P0005": "Fuel Shutoff Valve A Control Circuit/Open",
    "P0006": "Fuel Shutoff Valve A Control Circuit Low",
    "P0007": "Fuel Shutoff Valve A Control Circuit High",
    "P0008": "Engine Position System Performance Bank 1",
    "P0009": "Engine Position System Performance Bank 2",
    "P0010": "Intake Camshaft Position Actuator Circuit/Open Bank 1",
    "P0011": "Intake Camshaft Position Timing Over-Advanced Bank 1",
    "P0012": "Intake Camshaft Position Timing Over-Retarded Bank 1",
    "P0013": "Exhaust Camshaft Position Actuator Circuit/Open Bank 1",
    "P0014": "Exhaust Camshaft Position Timing Over-Advanced Bank 1",
    "P0015": "Exhaust Camshaft Position Timing Over-Retarded Bank 1",
    "P0016": "Crankshaft Position - Camshaft Position Correlation Bank 1 Sensor A",
    "P0017": "Crankshaft Position - Camshaft Position Correlation Bank 1 Sensor B",
    "P0018": "Crankshaft Position - Camshaft Position Correlation Bank 2 Sensor A",
    "P0019": "Crankshaft Position - Camshaft Position Correlation Bank 2 Sensor B",
    "P0020": "Intake Camshaft Position Actuator Circuit/Open Bank 2",
    "P0021": "Intake Camshaft Position Timing Over-Advanced Bank 2",
    "P0022": "Intake Camshaft Position Timing Over-Retarded Bank 2",
    "P0023": "Exhaust Camshaft Position Actuator Circuit/Open Bank 2",
    "P0024": "Exhaust Camshaft Position Timing Over-Advanced Bank 2",
    "P0025": "Exhaust Camshaft Position Timing Over-Retarded Bank 2",
    "P0026": "Intake Valve Control Solenoid Circuit Range/Performance Bank 1",
    "P0027": "Exhaust Valve Control Solenoid Circuit Range/Performance Bank 1",
    "P0028": "Intake Valve Control Solenoid Circuit Range/Performance Bank 2",
    "P0029": "Exhaust Valve Control Solenoid Circuit Range/Performance Bank 2",
    "P0030": "HO2S Heater Control Circuit Bank 1 Sensor 1",
    "P0031": "HO2S Heater Control Circuit Low Bank 1 Sensor 1",
    "P0032": "HO2S Heater Control Circuit High Bank 1 Sensor 1",
    "P0033": "Turbocharger/Supercharger Bypass Valve Control Circuit/Open",
    "P0034": "Turbocharger/Supercharger Bypass Valve Control Circuit Low",
    "P0035": "Turbocharger/Supercharger Bypass Valve Control Circuit High",
    "P0036": "HO2S Heater Control Circuit Bank 1 Sensor 2",
    "P0037": "HO2S Heater Control Circuit Low Bank 1 Sensor 2",
    "P0038": "HO2S Heater Control Circuit High Bank 1 Sensor 2",
    "P0039": "Turbocharger/Supercharger Bypass Valve Control Circuit Range/Performance",
    "P0040": "O2 Sensor Signals Swapped Bank 1 Sensor 1 / Bank 2 Sensor 1",
    "P0041": "O2 Sensor Signals Swapped Bank 1 Sensor 2 / Bank 2 Sensor 2",
    "P0042": "HO2S Heater Control Circuit Bank 1 Sensor 3",
    "P0043": "HO2S Heater Control Circuit Low Bank 1 Sensor 3",
    "P0044": "HO2S Heater Control Circuit High Bank 1 Sensor 3",
    "P0045": "Turbocharger/Supercharger Boost Control Solenoid Circuit/Open",
    "P0046": "Turbocharger/Supercharger Boost Control Solenoid Circuit Range/Performance",
    "P0047": "Turbocharger/Supercharger Boost Control Solenoid Circuit Low",
    "P0048": "Turbocharger/Supercharger Boost Control Solenoid Circuit High",
    "P0049": "Turbocharger/Supercharger Turbine Overspeed",
    "P0050": "HO2S Heater Control Circuit Bank 2 Sensor 1",
    "P0051": "HO2S Heater Control Circuit Low Bank 2 Sensor 1",
    "P0052": "HO2S Heater Control Circuit High Bank 2 Sensor 1",
    "P0053": "HO2S Heater Resistance Bank 1 Sensor 1",
    "P0054": "HO2S Heater Resistance Bank 1 Sensor 2",
    "P0055": "HO2S Heater Resistance Bank 1 Sensor 3",
    "P0056": "HO2S Heater Control Circuit Bank 2 Sensor 2",
    "P0057": "HO2S Heater Control Circuit Low Bank 2 Sensor 2",
    "P0058": "HO2S Heater Control Circuit High Bank 2 Sensor 2",
    "P0059": "HO2S Heater Resistance Bank 2 Sensor 1",
    "P0060": "HO2S Heater Resistance Bank 2 Sensor 2",
    "P0061": "HO2S Heater Resistance Bank 2 Sensor 3",
    "P0062": "HO2S Heater Control Circuit Bank 2 Sensor 3",
    "P0063": "HO2S Heater Control Circuit Low Bank 2 Sensor 3",
    "P0064": "HO2S Heater Control Circuit High Bank 2 Sensor 3",
    "P0065": "Air Assisted Injector Control Range/Performance",
    "P0066": "Air Assisted Injector Control Circuit or Circuit Low",
    "P0067": "Air Assisted Injector Control Circuit High",
    "P0068": "MAP/MAF - Throttle Position Correlation",
    "P0069": "Manifold Absolute Pressure - Barometric Pressure Correlation",
    "P0070": "Ambient Air Temperature Sensor Circuit",
    "P0071": "Ambient Air Temperature Sensor Range/Performance",
    "P0072": "Ambient Air Temperature Sensor Circuit Low",
    "P0073": "Ambient Air Temperature Sensor Circuit High",
    "P0074": "Ambient Air Temperature Sensor Circuit Intermittent",
    "P0075": "Intake Valve Control Solenoid Circuit Bank 1",
    "P0076": "Intake Valve Control Solenoid Circuit Low Bank 1",
    "P0077": "Intake Valve Control Solenoid Circuit High Bank 1",
    "P0078": "Exhaust Valve Control Solenoid Circuit Bank 1",
    "P0079": "Exhaust Valve Control Solenoid Circuit Low Bank 1",
    "P0080": "Exhaust Valve Control Solenoid Circuit High Bank 1",
    "P0081": "Intake Valve Control Solenoid Circuit Bank 2",
    "P0082": "Intake Valve Control Solenoid Circuit Low Bank 2",
    "P0083": "Intake Valve Control Solenoid Circuit High Bank 2",
    "P0084": "Exhaust Valve Control Solenoid Circuit Bank 2",
    "P0085": "Exhaust Valve Control Solenoid Circuit Low Bank 2",
    "P0086": "Exhaust Valve Control Solenoid Circuit High Bank 2",
    "P0087": "Fuel Rail/System Pressure - Too Low",
    "P0088": "Fuel Rail/System Pressure - Too High",
    "P0089": "Fuel Pressure Regulator 1 Performance",
    "P0090": "Fuel Pressure Regulator 1 Control Circuit",
    "P0091": "Fuel Pressure Regulator 1 Control Circuit Low",
    "P0092": "Fuel Pressure Regulator 1 Control Circuit High",
    "P0093": "Fuel System Leak Detected - Large Leak",
    "P0094": "Fuel System Leak Detected - Small Leak",
    "P0095": "Intake Air Temperature Sensor 2 Circuit",
    "P0096": "Intake Air Temperature Sensor 2 Circuit Range/Performance",
    "P0097": "Intake Air Temperature Sensor 2 Circuit Low",
    "P0098": "Intake Air Temperature Sensor 2 Circuit High",
    "P0099": "Intake Air Temperature Sensor 2 Circuit Intermittent/Erratic",

    # ---- P01xx: Fuel and Air Metering ----
    "P0100": "Mass or Volume Air Flow Circuit Malfunction",
    "P0101": "Mass or Volume Air Flow Circuit Range/Performance Problem",
    "P0102": "Mass or Volume Air Flow Circuit Low Input",
    "P0103": "Mass or Volume Air Flow Circuit High Input",
    "P0104": "Mass or Volume Air Flow Circuit Intermittent",
    "P0105": "Manifold Absolute Pressure/Barometric Pressure Circuit Malfunction",
    "P0106": "Manifold Absolute Pressure/Barometric Pressure Circuit Range/Performance",
    "P0107": "Manifold Absolute Pressure/Barometric Pressure Circuit Low Input",
    "P0108": "Manifold Absolute Pressure/Barometric Pressure Circuit High Input",
    "P0109": "Manifold Absolute Pressure/Barometric Pressure Circuit Intermittent",
    "P0110": "Intake Air Temperature Circuit Malfunction",
    "P0111": "Intake Air Temperature Circuit Range/Performance Problem",
    "P0112": "Intake Air Temperature Circuit Low Input",
    "P0113": "Intake Air Temperature Circuit High Input",
    "P0114": "Intake Air Temperature Circuit Intermittent",
    "P0115": "Engine Coolant Temperature Circuit Malfunction",
    "P0116": "Engine Coolant Temperature Circuit Range/Performance Problem",
    "P0117": "Engine Coolant Temperature Circuit Low Input",
    "P0118": "Engine Coolant Temperature Circuit High Input",
    "P0119": "Engine Coolant Temperature Circuit Intermittent",
    "P0120": "Throttle/Pedal Position Sensor/Switch A Circuit Malfunction",
    "P0121": "Throttle/Pedal Position Sensor/Switch A Circuit Range/Performance",
    "P0122": "Throttle/Pedal Position Sensor/Switch A Circuit Low Input",
    "P0123": "Throttle/Pedal Position Sensor/Switch A Circuit High Input",
    "P0124": "Throttle/Pedal Position Sensor/Switch A Circuit Intermittent",
    "P0125": "Insufficient Coolant Temperature for Closed Loop Fuel Control",
    "P0126": "Insufficient Coolant Temperature for Stable Operation",
    "P0127": "Intake Air Temperature Too High",
    "P0128": "Coolant Thermostat (Coolant Temp Below Thermostat Regulating Temp)",
    "P0129": "Barometric Pressure Too Low",
    "P0130": "O2 Sensor Circuit Malfunction Bank 1 Sensor 1",
    "P0131": "O2 Sensor Circuit Low Voltage Bank 1 Sensor 1",
    "P0132": "O2 Sensor Circuit High Voltage Bank 1 Sensor 1",
    "P0133": "O2 Sensor Circuit Slow Response Bank 1 Sensor 1",
    "P0134": "O2 Sensor Circuit No Activity Detected Bank 1 Sensor 1",
    "P0135": "O2 Sensor Heater Circuit Malfunction Bank 1 Sensor 1",
    "P0136": "O2 Sensor Circuit Malfunction Bank 1 Sensor 2",
    "P0137": "O2 Sensor Circuit Low Voltage Bank 1 Sensor 2",
    "P0138": "O2 Sensor Circuit High Voltage Bank 1 Sensor 2",
    "P0139": "O2 Sensor Circuit Slow Response Bank 1 Sensor 2",
    "P0140": "O2 Sensor Circuit No Activity Detected Bank 1 Sensor 2",
    "P0141": "O2 Sensor Heater Circuit Malfunction Bank 1 Sensor 2",
    "P0142": "O2 Sensor Circuit Malfunction Bank 1 Sensor 3",
    "P0143": "O2 Sensor Circuit Low Voltage Bank 1 Sensor 3",
    "P0144": "O2 Sensor Circuit High Voltage Bank 1 Sensor 3",
    "P0145": "O2 Sensor Circuit Slow Response Bank 1 Sensor 3",
    "P0146": "O2 Sensor Circuit No Activity Detected Bank 1 Sensor 3",
    "P0147": "O2 Sensor Heater Circuit Malfunction Bank 1 Sensor 3",
    "P0148": "Fuel Delivery Error",
    "P0149": "Fuel Timing Error",
    "P0150": "O2 Sensor Circuit Malfunction Bank 2 Sensor 1",
    "P0151": "O2 Sensor Circuit Low Voltage Bank 2 Sensor 1",
    "P0152": "O2 Sensor Circuit High Voltage Bank 2 Sensor 1",
    "P0153": "O2 Sensor Circuit Slow Response Bank 2 Sensor 1",
    "P0154": "O2 Sensor Circuit No Activity Detected Bank 2 Sensor 1",
    "P0155": "O2 Sensor Heater Circuit Malfunction Bank 2 Sensor 1",
    "P0156": "O2 Sensor Circuit Malfunction Bank 2 Sensor 2",
    "P0157": "O2 Sensor Circuit Low Voltage Bank 2 Sensor 2",
    "P0158": "O2 Sensor Circuit High Voltage Bank 2 Sensor 2",
    "P0159": "O2 Sensor Circuit Slow Response Bank 2 Sensor 2",
    "P0160": "O2 Sensor Circuit No Activity Detected Bank 2 Sensor 2",
    "P0161": "O2 Sensor Heater Circuit Malfunction Bank 2 Sensor 2",
    "P0162": "O2 Sensor Circuit Malfunction Bank 2 Sensor 3",
    "P0163": "O2 Sensor Circuit Low Voltage Bank 2 Sensor 3",
    "P0164": "O2 Sensor Circuit High Voltage Bank 2 Sensor 3",
    "P0165": "O2 Sensor Circuit Slow Response Bank 2 Sensor 3",
    "P0166": "O2 Sensor Circuit No Activity Detected Bank 2 Sensor 3",
    "P0167": "O2 Sensor Heater Circuit Malfunction Bank 2 Sensor 3",
    "P0168": "Fuel Temperature Too High",
    "P0169": "Incorrect Fuel Composition",
    "P0170": "Fuel Trim Malfunction Bank 1",
    "P0171": "System Too Lean Bank 1",
    "P0172": "System Too Rich Bank 1",
    "P0173": "Fuel Trim Malfunction Bank 2",
    "P0174": "System Too Lean Bank 2",
    "P0175": "System Too Rich Bank 2",
    "P0176": "Fuel Composition Sensor Circuit Malfunction",
    "P0177": "Fuel Composition Sensor Circuit Range/Performance",
    "P0178": "Fuel Composition Sensor Circuit Low Input",
    "P0179": "Fuel Composition Sensor Circuit High Input",
    "P0180": "Fuel Temperature Sensor A Circuit Malfunction",
    "P0181": "Fuel Temperature Sensor A Circuit Range/Performance",
    "P0182": "Fuel Temperature Sensor A Circuit Low Input",
    "P0183": "Fuel Temperature Sensor A Circuit High Input",
    "P0184": "Fuel Temperature Sensor A Circuit Intermittent",
    "P0185": "Fuel Temperature Sensor B Circuit Malfunction",
    "P0186": "Fuel Temperature Sensor B Circuit Range/Performance",
    "P0187": "Fuel Temperature Sensor B Circuit Low Input",
    "P0188": "Fuel Temperature Sensor B Circuit High Input",
    "P0189": "Fuel Temperature Sensor B Circuit Intermittent",
    "P0190": "Fuel Rail Pressure Sensor Circuit Malfunction",
    "P0191": "Fuel Rail Pressure Sensor Circuit Range/Performance",
    "P0192": "Fuel Rail Pressure Sensor Circuit Low Input",
    "P0193": "Fuel Rail Pressure Sensor Circuit High Input",
    "P0194": "Fuel Rail Pressure Sensor Circuit Intermittent",
    "P0195": "Engine Oil Temperature Sensor Malfunction",
    "P0196": "Engine Oil Temperature Sensor Range/Performance",
    "P0197": "Engine Oil Temperature Sensor Low",
    "P0198": "Engine Oil Temperature Sensor High",
    "P0199": "Engine Oil Temperature Sensor Intermittent",

    # ---- P02xx: Fuel and Air Metering (Injector Circuit) ----
    "P0200": "Injector Circuit Malfunction",
    "P0201": "Injector Circuit Malfunction - Cylinder 1",
    "P0202": "Injector Circuit Malfunction - Cylinder 2",
    "P0203": "Injector Circuit Malfunction - Cylinder 3",
    "P0204": "Injector Circuit Malfunction - Cylinder 4",
    "P0205": "Injector Circuit Malfunction - Cylinder 5",
    "P0206": "Injector Circuit Malfunction - Cylinder 6",
    "P0207": "Injector Circuit Malfunction - Cylinder 7",
    "P0208": "Injector Circuit Malfunction - Cylinder 8",
    "P0209": "Injector Circuit Malfunction - Cylinder 9",
    "P0210": "Injector Circuit Malfunction - Cylinder 10",
    "P0211": "Injector Circuit Malfunction - Cylinder 11",
    "P0212": "Injector Circuit Malfunction - Cylinder 12",
    "P0213": "Cold Start Injector 1 Malfunction",
    "P0214": "Cold Start Injector 2 Malfunction",
    "P0215": "Engine Shutoff Solenoid Malfunction",
    "P0216": "Injection Timing Control Circuit Malfunction",
    "P0217": "Engine Coolant Over Temperature Condition",
    "P0218": "Transmission Fluid Over Temperature Condition",
    "P0219": "Engine Overspeed Condition",
    "P0220": "Throttle/Pedal Position Sensor/Switch B Circuit Malfunction",
    "P0221": "Throttle/Pedal Position Sensor/Switch B Circuit Range/Performance",
    "P0222": "Throttle/Pedal Position Sensor/Switch B Circuit Low Input",
    "P0223": "Throttle/Pedal Position Sensor/Switch B Circuit High Input",
    "P0224": "Throttle/Pedal Position Sensor/Switch B Circuit Intermittent",
    "P0225": "Throttle/Pedal Position Sensor/Switch C Circuit Malfunction",
    "P0226": "Throttle/Pedal Position Sensor/Switch C Circuit Range/Performance",
    "P0227": "Throttle/Pedal Position Sensor/Switch C Circuit Low Input",
    "P0228": "Throttle/Pedal Position Sensor/Switch C Circuit High Input",
    "P0229": "Throttle/Pedal Position Sensor/Switch C Circuit Intermittent",
    "P0230": "Fuel Pump Primary Circuit Malfunction",
    "P0231": "Fuel Pump Secondary Circuit Low",
    "P0232": "Fuel Pump Secondary Circuit High",
    "P0233": "Fuel Pump Secondary Circuit Intermittent",
    "P0234": "Turbocharger/Supercharger Overboost Condition",
    "P0235": "Turbocharger/Supercharger Boost Sensor A Circuit Malfunction",
    "P0236": "Turbocharger/Supercharger Boost Sensor A Circuit Range/Performance",
    "P0237": "Turbocharger/Supercharger Boost Sensor A Circuit Low",
    "P0238": "Turbocharger/Supercharger Boost Sensor A Circuit High",
    "P0239": "Turbocharger/Supercharger Boost Sensor B Circuit Malfunction",
    "P0240": "Turbocharger/Supercharger Boost Sensor B Circuit Range/Performance",
    "P0241": "Turbocharger/Supercharger Boost Sensor B Circuit Low",
    "P0242": "Turbocharger/Supercharger Boost Sensor B Circuit High",
    "P0243": "Turbocharger/Supercharger Wastegate Solenoid A Malfunction",
    "P0244": "Turbocharger/Supercharger Wastegate Solenoid A Range/Performance",
    "P0245": "Turbocharger/Supercharger Wastegate Solenoid A Low",
    "P0246": "Turbocharger/Supercharger Wastegate Solenoid A High",
    "P0247": "Turbocharger/Supercharger Wastegate Solenoid B Malfunction",
    "P0248": "Turbocharger/Supercharger Wastegate Solenoid B Range/Performance",
    "P0249": "Turbocharger/Supercharger Wastegate Solenoid B Low",
    "P0250": "Turbocharger/Supercharger Wastegate Solenoid B High",
    "P0251": "Injection Pump Fuel Metering Control A Malfunction (Cam/Rotor/Injector)",
    "P0252": "Injection Pump Fuel Metering Control A Range/Performance",
    "P0253": "Injection Pump Fuel Metering Control A Low",
    "P0254": "Injection Pump Fuel Metering Control A High",
    "P0255": "Injection Pump Fuel Metering Control A Intermittent",
    "P0256": "Injection Pump Fuel Metering Control B Malfunction (Cam/Rotor/Injector)",
    "P0257": "Injection Pump Fuel Metering Control B Range/Performance",
    "P0258": "Injection Pump Fuel Metering Control B Low",
    "P0259": "Injection Pump Fuel Metering Control B High",
    "P0260": "Injection Pump Fuel Metering Control B Intermittent",
    "P0261": "Cylinder 1 Injector Circuit Low",
    "P0262": "Cylinder 1 Injector Circuit High",
    "P0263": "Cylinder 1 Contribution/Balance Fault",
    "P0264": "Cylinder 2 Injector Circuit Low",
    "P0265": "Cylinder 2 Injector Circuit High",
    "P0266": "Cylinder 2 Contribution/Balance Fault",
    "P0267": "Cylinder 3 Injector Circuit Low",
    "P0268": "Cylinder 3 Injector Circuit High",
    "P0269": "Cylinder 3 Contribution/Balance Fault",
    "P0270": "Cylinder 4 Injector Circuit Low",
    "P0271": "Cylinder 4 Injector Circuit High",
    "P0272": "Cylinder 4 Contribution/Balance Fault",
    "P0273": "Cylinder 5 Injector Circuit Low",
    "P0274": "Cylinder 5 Injector Circuit High",
    "P0275": "Cylinder 5 Contribution/Balance Fault",
    "P0276": "Cylinder 6 Injector Circuit Low",
    "P0277": "Cylinder 6 Injector Circuit High",
    "P0278": "Cylinder 6 Contribution/Balance Fault",
    "P0279": "Cylinder 7 Injector Circuit Low",
    "P0280": "Cylinder 7 Injector Circuit High",
    "P0281": "Cylinder 7 Contribution/Balance Fault",
    "P0282": "Cylinder 8 Injector Circuit Low",
    "P0283": "Cylinder 8 Injector Circuit High",
    "P0284": "Cylinder 8 Contribution/Balance Fault",
    "P0285": "Cylinder 9 Injector Circuit Low",
    "P0286": "Cylinder 9 Injector Circuit High",
    "P0287": "Cylinder 9 Contribution/Balance Fault",
    "P0288": "Cylinder 10 Injector Circuit Low",
    "P0289": "Cylinder 10 Injector Circuit High",
    "P0290": "Cylinder 10 Contribution/Balance Fault",
    "P0291": "Cylinder 11 Injector Circuit Low",
    "P0292": "Cylinder 11 Injector Circuit High",
    "P0293": "Cylinder 11 Contribution/Balance Fault",
    "P0294": "Cylinder 12 Injector Circuit Low",
    "P0295": "Cylinder 12 Injector Circuit High",
    "P0296": "Cylinder 12 Contribution/Balance Fault",
    "P0297": "Vehicle Overspeed Condition",
    "P0298": "Engine Oil Over Temperature Condition",
    "P0299": "Turbocharger/Supercharger Underboost Condition",

    # ---- P03xx: Ignition System or Misfire ----
    "P0300": "Random/Multiple Cylinder Misfire Detected",
    "P0301": "Cylinder 1 Misfire Detected",
    "P0302": "Cylinder 2 Misfire Detected",
    "P0303": "Cylinder 3 Misfire Detected",
    "P0304": "Cylinder 4 Misfire Detected",
    "P0305": "Cylinder 5 Misfire Detected",
    "P0306": "Cylinder 6 Misfire Detected",
    "P0307": "Cylinder 7 Misfire Detected",
    "P0308": "Cylinder 8 Misfire Detected",
    "P0309": "Cylinder 9 Misfire Detected",
    "P0310": "Cylinder 10 Misfire Detected",
    "P0311": "Cylinder 11 Misfire Detected",
    "P0312": "Cylinder 12 Misfire Detected",
    "P0313": "Misfire Detected with Low Fuel",
    "P0314": "Single Cylinder Misfire (Cylinder Not Specified)",
    "P0315": "Crankshaft Position System Variation Not Learned",
    "P0316": "Engine Misfire Detected on Startup (First 1000 Revolutions)",
    "P0317": "Rough Road Hardware Not Present",
    "P0318": "Rough Road Sensor A Signal Circuit",
    "P0319": "Rough Road Sensor B Signal Circuit",
    "P0320": "Ignition/Distributor Engine Speed Input Circuit Malfunction",
    "P0321": "Ignition/Distributor Engine Speed Input Circuit Range/Performance",
    "P0322": "Ignition/Distributor Engine Speed Input Circuit No Signal",
    "P0323": "Ignition/Distributor Engine Speed Input Circuit Intermittent",
    "P0324": "Knock Control System Error",
    "P0325": "Knock Sensor 1 Circuit Malfunction (Bank 1 or Single Sensor)",
    "P0326": "Knock Sensor 1 Circuit Range/Performance (Bank 1 or Single Sensor)",
    "P0327": "Knock Sensor 1 Circuit Low Input (Bank 1 or Single Sensor)",
    "P0328": "Knock Sensor 1 Circuit High Input (Bank 1 or Single Sensor)",
    "P0329": "Knock Sensor 1 Circuit Intermittent (Bank 1 or Single Sensor)",
    "P0330": "Knock Sensor 2 Circuit Malfunction (Bank 2)",
    "P0331": "Knock Sensor 2 Circuit Range/Performance (Bank 2)",
    "P0332": "Knock Sensor 2 Circuit Low Input (Bank 2)",
    "P0333": "Knock Sensor 2 Circuit High Input (Bank 2)",
    "P0334": "Knock Sensor 2 Circuit Intermittent (Bank 2)",
    "P0335": "Crankshaft Position Sensor A Circuit Malfunction",
    "P0336": "Crankshaft Position Sensor A Circuit Range/Performance",
    "P0337": "Crankshaft Position Sensor A Circuit Low Input",
    "P0338": "Crankshaft Position Sensor A Circuit High Input",
    "P0339": "Crankshaft Position Sensor A Circuit Intermittent",
    "P0340": "Camshaft Position Sensor A Circuit Malfunction (Bank 1 or Single Sensor)",
    "P0341": "Camshaft Position Sensor A Circuit Range/Performance (Bank 1 or Single Sensor)",
    "P0342": "Camshaft Position Sensor A Circuit Low Input (Bank 1 or Single Sensor)",
    "P0343": "Camshaft Position Sensor A Circuit High Input (Bank 1 or Single Sensor)",
    "P0344": "Camshaft Position Sensor A Circuit Intermittent (Bank 1 or Single Sensor)",
    "P0345": "Camshaft Position Sensor A Circuit Malfunction (Bank 2)",
    "P0346": "Camshaft Position Sensor A Circuit Range/Performance (Bank 2)",
    "P0347": "Camshaft Position Sensor A Circuit Low Input (Bank 2)",
    "P0348": "Camshaft Position Sensor A Circuit High Input (Bank 2)",
    "P0349": "Camshaft Position Sensor A Circuit Intermittent (Bank 2)",
    "P0350": "Ignition Coil Primary/Secondary Circuit Malfunction",
    "P0351": "Ignition Coil A Primary/Secondary Circuit Malfunction",
    "P0352": "Ignition Coil B Primary/Secondary Circuit Malfunction",
    "P0353": "Ignition Coil C Primary/Secondary Circuit Malfunction",
    "P0354": "Ignition Coil D Primary/Secondary Circuit Malfunction",
    "P0355": "Ignition Coil E Primary/Secondary Circuit Malfunction",
    "P0356": "Ignition Coil F Primary/Secondary Circuit Malfunction",
    "P0357": "Ignition Coil G Primary/Secondary Circuit Malfunction",
    "P0358": "Ignition Coil H Primary/Secondary Circuit Malfunction",
    "P0359": "Ignition Coil I Primary/Secondary Circuit Malfunction",
    "P0360": "Ignition Coil J Primary/Secondary Circuit Malfunction",
    "P0361": "Ignition Coil K Primary/Secondary Circuit Malfunction",
    "P0362": "Ignition Coil L Primary/Secondary Circuit Malfunction",
    "P0363": "Misfire Detected - Fueling Disabled",
    "P0365": "Camshaft Position Sensor B Circuit (Bank 1)",
    "P0366": "Camshaft Position Sensor B Circuit Range/Performance (Bank 1)",
    "P0367": "Camshaft Position Sensor B Circuit Low (Bank 1)",
    "P0368": "Camshaft Position Sensor B Circuit High (Bank 1)",
    "P0369": "Camshaft Position Sensor B Circuit Intermittent (Bank 1)",
    "P0370": "Timing Reference High Resolution Signal A Malfunction",
    "P0371": "Timing Reference High Resolution Signal A Too Many Pulses",
    "P0372": "Timing Reference High Resolution Signal A Too Few Pulses",
    "P0373": "Timing Reference High Resolution Signal A Intermittent/Erratic Pulses",
    "P0374": "Timing Reference High Resolution Signal A No Pulses",
    "P0375": "Timing Reference High Resolution Signal B Malfunction",
    "P0376": "Timing Reference High Resolution Signal B Too Many Pulses",
    "P0377": "Timing Reference High Resolution Signal B Too Few Pulses",
    "P0378": "Timing Reference High Resolution Signal B Intermittent/Erratic Pulses",
    "P0379": "Timing Reference High Resolution Signal B No Pulses",
    "P0380": "Glow Plug/Heater Circuit A Malfunction",
    "P0381": "Glow Plug/Heater Indicator Circuit Malfunction",
    "P0382": "Glow Plug/Heater Circuit B Malfunction",
    "P0383": "Glow Plug/Heater Circuit B Low",
    "P0384": "Glow Plug/Heater Circuit B High",
    "P0385": "Crankshaft Position Sensor B Circuit Malfunction",
    "P0386": "Crankshaft Position Sensor B Circuit Range/Performance",
    "P0387": "Crankshaft Position Sensor B Circuit Low Input",
    "P0388": "Crankshaft Position Sensor B Circuit High Input",
    "P0389": "Crankshaft Position Sensor B Circuit Intermittent",
    "P0390": "Camshaft Position Sensor B Circuit (Bank 2)",
    "P0391": "Camshaft Position Sensor B Circuit Range/Performance (Bank 2)",
    "P0392": "Camshaft Position Sensor B Circuit Low (Bank 2)",
    "P0393": "Camshaft Position Sensor B Circuit High (Bank 2)",
    "P0394": "Camshaft Position Sensor B Circuit Intermittent (Bank 2)",

    # ---- P04xx: Auxiliary Emission Controls ----
    "P0400": "Exhaust Gas Recirculation Flow Malfunction",
    "P0401": "Exhaust Gas Recirculation Flow Insufficient Detected",
    "P0402": "Exhaust Gas Recirculation Flow Excessive Detected",
    "P0403": "Exhaust Gas Recirculation Circuit Malfunction",
    "P0404": "Exhaust Gas Recirculation Circuit Range/Performance",
    "P0405": "Exhaust Gas Recirculation Sensor A Circuit Low",
    "P0406": "Exhaust Gas Recirculation Sensor A Circuit High",
    "P0407": "Exhaust Gas Recirculation Sensor B Circuit Low",
    "P0408": "Exhaust Gas Recirculation Sensor B Circuit High",
    "P0409": "Exhaust Gas Recirculation Sensor A Circuit",
    "P0410": "Secondary Air Injection System Malfunction",
    "P0411": "Secondary Air Injection System Incorrect Flow Detected",
    "P0412": "Secondary Air Injection System Switching Valve A Circuit Malfunction",
    "P0413": "Secondary Air Injection System Switching Valve A Circuit Open",
    "P0414": "Secondary Air Injection System Switching Valve A Circuit Shorted",
    "P0415": "Secondary Air Injection System Switching Valve B Circuit Malfunction",
    "P0416": "Secondary Air Injection System Switching Valve B Circuit Open",
    "P0417": "Secondary Air Injection System Switching Valve B Circuit Shorted",
    "P0418": "Secondary Air Injection System Relay A Circuit Malfunction",
    "P0419": "Secondary Air Injection System Relay B Circuit Malfunction",
    "P0420": "Catalyst System Efficiency Below Threshold Bank 1",
    "P0421": "Warm Up Catalyst Efficiency Below Threshold Bank 1",
    "P0422": "Main Catalyst Efficiency Below Threshold Bank 1",
    "P0423": "Heated Catalyst Efficiency Below Threshold Bank 1",
    "P0424": "Heated Catalyst Temperature Below Threshold Bank 1",
    "P0425": "Catalyst Temperature Sensor Bank 1",
    "P0426": "Catalyst Temperature Sensor Range/Performance Bank 1",
    "P0427": "Catalyst Temperature Sensor Low Input Bank 1",
    "P0428": "Catalyst Temperature Sensor High Input Bank 1",
    "P0429": "Catalyst Heater Control Circuit Bank 1",
    "P0430": "Catalyst System Efficiency Below Threshold Bank 2",
    "P0431": "Warm Up Catalyst Efficiency Below Threshold Bank 2",
    "P0432": "Main Catalyst Efficiency Below Threshold Bank 2",
    "P0433": "Heated Catalyst Efficiency Below Threshold Bank 2",
    "P0434": "Heated Catalyst Temperature Below Threshold Bank 2",
    "P0435": "Catalyst Temperature Sensor Bank 2",
    "P0436": "Catalyst Temperature Sensor Range/Performance Bank 2",
    "P0437": "Catalyst Temperature Sensor Low Input Bank 2",
    "P0438": "Catalyst Temperature Sensor High Input Bank 2",
    "P0439": "Catalyst Heater Control Circuit Bank 2",
    "P0440": "Evaporative Emission Control System Malfunction",
    "P0441": "Evaporative Emission Control System Incorrect Purge Flow",
    "P0442": "Evaporative Emission Control System Leak Detected (Small Leak)",
    "P0443": "Evaporative Emission Control System Purge Control Valve Circuit Malfunction",
    "P0444": "Evaporative Emission Control System Purge Control Valve Circuit Open",
    "P0445": "Evaporative Emission Control System Purge Control Valve Circuit Shorted",
    "P0446": "Evaporative Emission Control System Vent Control Circuit Malfunction",
    "P0447": "Evaporative Emission Control System Vent Control Circuit Open",
    "P0448": "Evaporative Emission Control System Vent Control Circuit Shorted",
    "P0449": "Evaporative Emission Control System Vent Valve/Solenoid Circuit Malfunction",
    "P0450": "Evaporative Emission Control System Pressure Sensor Malfunction",
    "P0451": "Evaporative Emission Control System Pressure Sensor Range/Performance",
    "P0452": "Evaporative Emission Control System Pressure Sensor Low Input",
    "P0453": "Evaporative Emission Control System Pressure Sensor High Input",
    "P0454": "Evaporative Emission Control System Pressure Sensor Intermittent",
    "P0455": "Evaporative Emission Control System Leak Detected (Gross Leak)",
    "P0456": "Evaporative Emission Control System Leak Detected (Very Small Leak)",
    "P0457": "Evaporative Emission Control System Leak Detected (Fuel Cap Loose/Off)",
    "P0458": "Evaporative Emission Control System Purge Control Valve Circuit Low",
    "P0459": "Evaporative Emission Control System Purge Control Valve Circuit High",
    "P0460": "Fuel Level Sensor Circuit Malfunction",
    "P0461": "Fuel Level Sensor Circuit Range/Performance",
    "P0462": "Fuel Level Sensor Circuit Low Input",
    "P0463": "Fuel Level Sensor Circuit High Input",
    "P0464": "Fuel Level Sensor Circuit Intermittent",
    "P0465": "Purge Flow Sensor Circuit Malfunction",
    "P0466": "Purge Flow Sensor Circuit Range/Performance",
    "P0467": "Purge Flow Sensor Circuit Low Input",
    "P0468": "Purge Flow Sensor Circuit High Input",
    "P0469": "Purge Flow Sensor Circuit Intermittent",
    "P0470": "Exhaust Pressure Sensor Malfunction",
    "P0471": "Exhaust Pressure Sensor Range/Performance",
    "P0472": "Exhaust Pressure Sensor Low",
    "P0473": "Exhaust Pressure Sensor High",
    "P0474": "Exhaust Pressure Sensor Intermittent",
    "P0475": "Exhaust Pressure Control Valve Malfunction",
    "P0476": "Exhaust Pressure Control Valve Range/Performance",
    "P0477": "Exhaust Pressure Control Valve Low",
    "P0478": "Exhaust Pressure Control Valve High",
    "P0479": "Exhaust Pressure Control Valve Intermittent",
    "P0480": "Cooling Fan 1 Control Circuit Malfunction",
    "P0481": "Cooling Fan 2 Control Circuit Malfunction",
    "P0482": "Cooling Fan 3 Control Circuit Malfunction",
    "P0483": "Cooling Fan Rationality Check Malfunction",
    "P0484": "Cooling Fan Circuit Over Current",
    "P0485": "Cooling Fan Power/Ground Circuit Malfunction",
    "P0486": "Exhaust Gas Recirculation Sensor B Circuit",
    "P0487": "Exhaust Gas Recirculation Throttle Position Control Circuit",
    "P0488": "Exhaust Gas Recirculation Throttle Position Control Range/Performance",
    "P0489": "Exhaust Gas Recirculation Control Circuit Low",
    "P0490": "Exhaust Gas Recirculation Control Circuit High",
    "P0491": "Secondary Air Injection System Insufficient Flow Bank 1",
    "P0492": "Secondary Air Injection System Insufficient Flow Bank 2",
    "P0493": "Cooling Fan Speed Exceeded",
    "P0494": "Cooling Fan Speed Low",
    "P0495": "Cooling Fan Speed High",
    "P0496": "Evaporative Emission System High Purge Flow",
    "P0497": "Evaporative Emission System Low Purge Flow",
    "P0498": "Evaporative Emission System Vent Valve Control Circuit Low",
    "P0499": "Evaporative Emission System Vent Valve Control Circuit High",

    # ---- P05xx: Vehicle Speed, Idle Control, Auxiliary Inputs ----
    "P0500": "Vehicle Speed Sensor Malfunction",
    "P0501": "Vehicle Speed Sensor Range/Performance",
    "P0502": "Vehicle Speed Sensor Circuit Low Input",
    "P0503": "Vehicle Speed Sensor Intermittent/Erratic/High",
    "P0504": "Brake Switch A/B Correlation",
    "P0505": "Idle Control System Malfunction",
    "P0506": "Idle Control System RPM Lower Than Expected",
    "P0507": "Idle Control System RPM Higher Than Expected",
    "P0508": "Idle Air Control System Circuit Low",
    "P0509": "Idle Air Control System Circuit High",
    "P0510": "Closed Throttle Position Switch Malfunction",
    "P0511": "Idle Air Control Circuit",
    "P0512": "Starter Request Circuit",
    "P0513": "Incorrect Immobilizer Key",
    "P0514": "Battery Temperature Sensor Circuit Range/Performance",
    "P0515": "Battery Temperature Sensor Circuit",
    "P0516": "Battery Temperature Sensor Circuit Low",
    "P0517": "Battery Temperature Sensor Circuit High",
    "P0518": "Idle Air Control Circuit Intermittent",
    "P0519": "Idle Air Control System Performance",
    "P0520": "Engine Oil Pressure Sensor/Switch Circuit Malfunction",
    "P0521": "Engine Oil Pressure Sensor/Switch Range/Performance",
    "P0522": "Engine Oil Pressure Sensor/Switch Low Voltage",
    "P0523": "Engine Oil Pressure Sensor/Switch High Voltage",
    "P0524": "Engine Oil Pressure Too Low",
    "P0525": "Cruise Control Servo Control Circuit Range/Performance",
    "P0526": "Cooling Fan Speed Sensor Circuit",
    "P0527": "Cooling Fan Speed Sensor Circuit Range/Performance",
    "P0528": "Cooling Fan Speed Sensor Circuit No Signal",
    "P0529": "Cooling Fan Speed Sensor Circuit Intermittent",
    "P0530": "A/C Refrigerant Pressure Sensor Circuit Malfunction",
    "P0531": "A/C Refrigerant Pressure Sensor Circuit Range/Performance",
    "P0532": "A/C Refrigerant Pressure Sensor Circuit Low Input",
    "P0533": "A/C Refrigerant Pressure Sensor Circuit High Input",
    "P0534": "Air Conditioner Refrigerant Charge Loss",
    "P0535": "A/C Evaporator Temperature Sensor Circuit",
    "P0536": "A/C Evaporator Temperature Sensor Circuit Range/Performance",
    "P0537": "A/C Evaporator Temperature Sensor Circuit Low",
    "P0538": "A/C Evaporator Temperature Sensor Circuit High",
    "P0539": "A/C Evaporator Temperature Sensor Circuit Intermittent",
    "P0540": "Intake Air Heater A Circuit Malfunction",
    "P0541": "Intake Air Heater A Circuit Low",
    "P0542": "Intake Air Heater A Circuit High",
    "P0543": "Intake Air Heater A Circuit Open",
    "P0544": "Exhaust Gas Temperature Sensor Circuit Bank 1 Sensor 1",
    "P0545": "Exhaust Gas Temperature Sensor Circuit Low Bank 1 Sensor 1",
    "P0546": "Exhaust Gas Temperature Sensor Circuit High Bank 1 Sensor 1",
    "P0547": "Exhaust Gas Temperature Sensor Circuit Bank 2 Sensor 1",
    "P0548": "Exhaust Gas Temperature Sensor Circuit Low Bank 2 Sensor 1",
    "P0549": "Exhaust Gas Temperature Sensor Circuit High Bank 2 Sensor 1",
    "P0550": "Power Steering Pressure Sensor Circuit Malfunction",
    "P0551": "Power Steering Pressure Sensor Circuit Range/Performance",
    "P0552": "Power Steering Pressure Sensor Circuit Low Input",
    "P0553": "Power Steering Pressure Sensor Circuit High Input",
    "P0554": "Power Steering Pressure Sensor Circuit Intermittent",
    "P0555": "Brake Booster Pressure Sensor Circuit",
    "P0556": "Brake Booster Pressure Sensor Circuit Range/Performance",
    "P0557": "Brake Booster Pressure Sensor Circuit Low Input",
    "P0558": "Brake Booster Pressure Sensor Circuit High Input",
    "P0559": "Brake Booster Pressure Sensor Circuit Intermittent",
    "P0560": "System Voltage Malfunction",
    "P0561": "System Voltage Unstable",
    "P0562": "System Voltage Low",
    "P0563": "System Voltage High",
    "P0564": "Cruise Control Multi-Function Input A Circuit",
    "P0565": "Cruise Control On Signal Malfunction",
    "P0566": "Cruise Control Off Signal Malfunction",
    "P0567": "Cruise Control Resume Signal Malfunction",
    "P0568": "Cruise Control Set Signal Malfunction",
    "P0569": "Cruise Control Coast Signal Malfunction",
    "P0570": "Cruise Control Accelerate Signal Malfunction",
    "P0571": "Cruise Control/Brake Switch A Circuit Malfunction",
    "P0572": "Cruise Control/Brake Switch A Circuit Low",
    "P0573": "Cruise Control/Brake Switch A Circuit High",
    "P0574": "Cruise Control System - Vehicle Speed Too High",
    "P0575": "Cruise Control Input Circuit",
    "P0576": "Cruise Control Input Circuit Low",
    "P0577": "Cruise Control Input Circuit High",
    "P0578": "Cruise Control Multi-Function Input A Circuit Stuck",
    "P0579": "Cruise Control Multi-Function Input A Circuit Range/Performance",
    "P0580": "Cruise Control Multi-Function Input A Circuit Low",
    "P0581": "Cruise Control Multi-Function Input A Circuit High",
    "P0582": "Cruise Control Vacuum Control Circuit/Open",
    "P0583": "Cruise Control Vacuum Control Circuit Low",
    "P0584": "Cruise Control Vacuum Control Circuit High",
    "P0585": "Cruise Control Multi-Function Input A/B Correlation",
    "P0586": "Cruise Control Vent Control Circuit/Open",
    "P0587": "Cruise Control Vent Control Circuit Low",
    "P0588": "Cruise Control Vent Control Circuit High",
    "P0589": "Cruise Control Multi-Function Input B Circuit",
    "P0590": "Cruise Control Multi-Function Input B Circuit Stuck",
    "P0591": "Cruise Control Multi-Function Input B Circuit Range/Performance",
    "P0592": "Cruise Control Multi-Function Input B Circuit Low",
    "P0593": "Cruise Control Multi-Function Input B Circuit High",
    "P0594": "Cruise Control Servo Control Circuit/Open",
    "P0595": "Cruise Control Servo Control Circuit Low",
    "P0596": "Cruise Control Servo Control Circuit High",
    "P0597": "Thermostat Heater Control Circuit/Open",
    "P0598": "Thermostat Heater Control Circuit Low",
    "P0599": "Thermostat Heater Control Circuit High",

    # ---- P06xx: Computer and Auxiliary Outputs ----
    "P0600": "Serial Communication Link Malfunction",
    "P0601": "Internal Control Module Memory Check Sum Error",
    "P0602": "Control Module Programming Error",
    "P0603": "Internal Control Module Keep Alive Memory (KAM) Error",
    "P0604": "Internal Control Module Random Access Memory (RAM) Error",
    "P0605": "Internal Control Module Read Only Memory (ROM) Error",
    "P0606": "ECM/PCM Processor Fault",
    "P0607": "Control Module Performance",
    "P0608": "Control Module VSS Output A Malfunction",
    "P0609": "Control Module VSS Output B Malfunction",
    "P0610": "Control Module Vehicle Options Error",
    "P0611": "Fuel Injector Control Module Performance",
    "P0612": "Fuel Injector Control Module Relay Control Circuit",
    "P0613": "Transmission Control Module (TCM) Processor",
    "P0614": "ECM/TCM Incompatible",
    "P0615": "Starter Relay Circuit",
    "P0616": "Starter Relay Circuit Low",
    "P0617": "Starter Relay Circuit High",
    "P0618": "Alternative Fuel Control Module KAM Error",
    "P0619": "Alternative Fuel Control Module RAM/ROM Error",
    "P0620": "Generator Control Circuit Malfunction",
    "P0621": "Generator Lamp/L Terminal Circuit Malfunction",
    "P0622": "Generator Field/F Terminal Circuit Malfunction",
    "P0623": "Generator Lamp Control Circuit",
    "P0624": "Fuel Cap Lamp Control Circuit",
    "P0625": "Generator Field/F Terminal Circuit Low",
    "P0626": "Generator Field/F Terminal Circuit High",
    "P0627": "Fuel Pump A Control Circuit/Open",
    "P0628": "Fuel Pump A Control Circuit Low",
    "P0629": "Fuel Pump A Control Circuit High",
    "P0630": "VIN Not Programmed or Incompatible - ECM/PCM",
    "P0631": "VIN Not Programmed or Incompatible - TCM",
    "P0632": "Odometer Not Programmed - ECM/PCM",
    "P0633": "Immobilizer Key Not Programmed - ECM/PCM",
    "P0634": "PCM/ECM/TCM Internal Temperature Too High",
    "P0635": "Power Steering Control Circuit",
    "P0636": "Power Steering Control Circuit Low",
    "P0637": "Power Steering Control Circuit High",
    "P0638": "Throttle Actuator Control Range/Performance Bank 1",
    "P0639": "Throttle Actuator Control Range/Performance Bank 2",
    "P0640": "Intake Air Heater Control Circuit",
    "P0641": "Sensor Reference Voltage A Circuit/Open",
    "P0642": "Sensor Reference Voltage A Circuit Low",
    "P0643": "Sensor Reference Voltage A Circuit High",
    "P0644": "Driver Display Serial Communication Circuit",
    "P0645": "A/C Clutch Relay Control Circuit",
    "P0646": "A/C Clutch Relay Control Circuit Low",
    "P0647": "A/C Clutch Relay Control Circuit High",
    "P0648": "Immobilizer Lamp Control Circuit",
    "P0649": "Speed Control Lamp Control Circuit",
    "P0650": "Malfunction Indicator Lamp (MIL) Control Circuit",
    "P0651": "Sensor Reference Voltage B Circuit/Open",
    "P0652": "Sensor Reference Voltage B Circuit Low",
    "P0653": "Sensor Reference Voltage B Circuit High",
    "P0654": "Engine RPM Output Circuit",
    "P0655": "Engine Hot Lamp Output Control Circuit",
    "P0656": "Fuel Level Output Circuit",
    "P0657": "Actuator Supply Voltage A Circuit/Open",
    "P0658": "Actuator Supply Voltage A Circuit Low",
    "P0659": "Actuator Supply Voltage A Circuit High",
    "P0660": "Intake Manifold Tuning Valve Control Circuit/Open Bank 1",
    "P0661": "Intake Manifold Tuning Valve Control Circuit Low Bank 1",
    "P0662": "Intake Manifold Tuning Valve Control Circuit High Bank 1",
    "P0663": "Intake Manifold Tuning Valve Control Circuit/Open Bank 2",
    "P0664": "Intake Manifold Tuning Valve Control Circuit Low Bank 2",
    "P0665": "Intake Manifold Tuning Valve Control Circuit High Bank 2",
    "P0666": "PCM/ECM/TCM Internal Temperature Sensor Circuit",
    "P0667": "PCM/ECM/TCM Internal Temperature Sensor Range/Performance",
    "P0668": "PCM/ECM/TCM Internal Temperature Sensor Circuit Low",
    "P0669": "PCM/ECM/TCM Internal Temperature Sensor Circuit High",
    "P0670": "Glow Plug Module Control Circuit",
    "P0671": "Cylinder 1 Glow Plug Circuit",
    "P0672": "Cylinder 2 Glow Plug Circuit",
    "P0673": "Cylinder 3 Glow Plug Circuit",
    "P0674": "Cylinder 4 Glow Plug Circuit",
    "P0675": "Cylinder 5 Glow Plug Circuit",
    "P0676": "Cylinder 6 Glow Plug Circuit",
    "P0677": "Cylinder 7 Glow Plug Circuit",
    "P0678": "Cylinder 8 Glow Plug Circuit",
    "P0679": "Cylinder 9 Glow Plug Circuit",
    "P0680": "Cylinder 10 Glow Plug Circuit",
    "P0681": "Cylinder 11 Glow Plug Circuit",
    "P0682": "Cylinder 12 Glow Plug Circuit",
    "P0683": "Glow Plug Control Module to PCM Communication Circuit",
    "P0684": "Glow Plug Control Module to PCM Communication Circuit Range/Performance",
    "P0685": "ECM/PCM Power Relay Control Circuit/Open",
    "P0686": "ECM/PCM Power Relay Control Circuit Low",
    "P0687": "ECM/PCM Power Relay Control Circuit High",
    "P0688": "ECM/PCM Power Relay Sense Circuit/Open",
    "P0689": "ECM/PCM Power Relay Sense Circuit Low",
    "P0690": "ECM/PCM Power Relay Sense Circuit High",
    "P0691": "Cooling Fan 1 Control Circuit Low",
    "P0692": "Cooling Fan 1 Control Circuit High",
    "P0693": "Cooling Fan 2 Control Circuit Low",
    "P0694": "Cooling Fan 2 Control Circuit High",
    "P0695": "Cooling Fan 3 Control Circuit Low",
    "P0696": "Cooling Fan 3 Control Circuit High",
    "P0697": "Sensor Reference Voltage C Circuit/Open",
    "P0698": "Sensor Reference Voltage C Circuit Low",
    "P0699": "Sensor Reference Voltage C Circuit High",

    # ---- P07xx: Transmission ----
    "P0700": "Transmission Control System Malfunction",
    "P0701": "Transmission Control System Range/Performance",
    "P0702": "Transmission Control System Electrical",
    "P0703": "Torque Converter/Brake Switch B Circuit Malfunction",
    "P0704": "Clutch Switch Input Circuit Malfunction",
    "P0705": "Transmission Range Sensor Circuit Malfunction (PRNDL Input)",
    "P0706": "Transmission Range Sensor Circuit Range/Performance",
    "P0707": "Transmission Range Sensor Circuit Low Input",
    "P0708": "Transmission Range Sensor Circuit High Input",
    "P0709": "Transmission Range Sensor Circuit Intermittent",
    "P0710": "Transmission Fluid Temperature Sensor Circuit Malfunction",
    "P0711": "Transmission Fluid Temperature Sensor Circuit Range/Performance",
    "P0712": "Transmission Fluid Temperature Sensor Circuit Low Input",
    "P0713": "Transmission Fluid Temperature Sensor Circuit High Input",
    "P0714": "Transmission Fluid Temperature Sensor Circuit Intermittent",
    "P0715": "Input/Turbine Speed Sensor Circuit Malfunction",
    "P0716": "Input/Turbine Speed Sensor Circuit Range/Performance",
    "P0717": "Input/Turbine Speed Sensor Circuit No Signal",
    "P0718": "Input/Turbine Speed Sensor Circuit Intermittent",
    "P0719": "Torque Converter/Brake Switch B Circuit Low",
    "P0720": "Output Speed Sensor Circuit Malfunction",
    "P0721": "Output Speed Sensor Circuit Range/Performance",
    "P0722": "Output Speed Sensor Circuit No Signal",
    "P0723": "Output Speed Sensor Circuit Intermittent",
    "P0724": "Torque Converter/Brake Switch B Circuit High",
    "P0725": "Engine Speed Input Circuit Malfunction",
    "P0726": "Engine Speed Input Circuit Range/Performance",
    "P0727": "Engine Speed Input Circuit No Signal",
    "P0728": "Engine Speed Input Circuit Intermittent",
    "P0729": "Gear 6 Incorrect Ratio",
    "P0730": "Incorrect Gear Ratio",
    "P0731": "Gear 1 Incorrect Ratio",
    "P0732": "Gear 2 Incorrect Ratio",
    "P0733": "Gear 3 Incorrect Ratio",
    "P0734": "Gear 4 Incorrect Ratio",
    "P0735": "Gear 5 Incorrect Ratio",
    "P0736": "Reverse Incorrect Ratio",
    "P0737": "TCM Engine Speed Output Circuit",
    "P0738": "TCM Engine Speed Output Circuit Low",
    "P0739": "TCM Engine Speed Output Circuit High",
    "P0740": "Torque Converter Clutch Circuit Malfunction",
    "P0741": "Torque Converter Clutch Circuit Performance or Stuck Off",
    "P0742": "Torque Converter Clutch Circuit Stuck On",
    "P0743": "Torque Converter Clutch Circuit Electrical",
    "P0744": "Torque Converter Clutch Circuit Intermittent",
    "P0745": "Pressure Control Solenoid A Malfunction",
    "P0746": "Pressure Control Solenoid A Performance or Stuck Off",
    "P0747": "Pressure Control Solenoid A Stuck On",
    "P0748": "Pressure Control Solenoid A Electrical",
    "P0749": "Pressure Control Solenoid A Intermittent",
    "P0750": "Shift Solenoid A Malfunction",
    "P0751": "Shift Solenoid A Performance or Stuck Off",
    "P0752": "Shift Solenoid A Stuck On",
    "P0753": "Shift Solenoid A Electrical",
    "P0754": "Shift Solenoid A Intermittent",
    "P0755": "Shift Solenoid B Malfunction",
    "P0756": "Shift Solenoid B Performance or Stuck Off",
    "P0757": "Shift Solenoid B Stuck On",
    "P0758": "Shift Solenoid B Electrical",
    "P0759": "Shift Solenoid B Intermittent",
    "P0760": "Shift Solenoid C Malfunction",
    "P0761": "Shift Solenoid C Performance or Stuck Off",
    "P0762": "Shift Solenoid C Stuck On",
    "P0763": "Shift Solenoid C Electrical",
    "P0764": "Shift Solenoid C Intermittent",
    "P0765": "Shift Solenoid D Malfunction",
    "P0766": "Shift Solenoid D Performance or Stuck Off",
    "P0767": "Shift Solenoid D Stuck On",
    "P0768": "Shift Solenoid D Electrical",
    "P0769": "Shift Solenoid D Intermittent",
    "P0770": "Shift Solenoid E Malfunction",
    "P0771": "Shift Solenoid E Performance or Stuck Off",
    "P0772": "Shift Solenoid E Stuck On",
    "P0773": "Shift Solenoid E Electrical",
    "P0774": "Shift Solenoid E Intermittent",
    "P0775": "Pressure Control Solenoid B Malfunction",
    "P0776": "Pressure Control Solenoid B Performance or Stuck Off",
    "P0777": "Pressure Control Solenoid B Stuck On",
    "P0778": "Pressure Control Solenoid B Electrical",
    "P0779": "Pressure Control Solenoid B Intermittent",
    "P0780": "Shift Malfunction",
    "P0781": "1-2 Shift Malfunction",
    "P0782": "2-3 Shift Malfunction",
    "P0783": "3-4 Shift Malfunction",
    "P0784": "4-5 Shift Malfunction",
    "P0785": "Shift/Timing Solenoid Malfunction",
    "P0786": "Shift/Timing Solenoid Range/Performance",
    "P0787": "Shift/Timing Solenoid Low",
    "P0788": "Shift/Timing Solenoid High",
    "P0789": "Shift/Timing Solenoid Intermittent",
    "P0790": "Normal/Performance Switch Circuit Malfunction",
    "P0791": "Intermediate Shaft Speed Sensor Circuit",
    "P0792": "Intermediate Shaft Speed Sensor Circuit Range/Performance",
    "P0793": "Intermediate Shaft Speed Sensor Circuit No Signal",
    "P0794": "Intermediate Shaft Speed Sensor Circuit Intermittent",
    "P0795": "Pressure Control Solenoid C Malfunction",
    "P0796": "Pressure Control Solenoid C Performance or Stuck Off",
    "P0797": "Pressure Control Solenoid C Stuck On",
    "P0798": "Pressure Control Solenoid C Electrical",
    "P0799": "Pressure Control Solenoid C Intermittent",

    # ---- P08xx: Transmission (continued) ----
    "P0800": "Transfer Case Control System (MIL Request)",
    "P0801": "Reverse Inhibit Control Circuit",
    "P0802": "Transmission Control System MIL Request Circuit/Open",
    "P0803": "1-4 Upshift (Skip Shift) Solenoid Control Circuit",
    "P0804": "1-4 Upshift (Skip Shift) Lamp Control Circuit",
    "P0805": "Clutch Position Sensor Circuit",
    "P0806": "Clutch Position Sensor Circuit Range/Performance",
    "P0807": "Clutch Position Sensor Circuit Low",
    "P0808": "Clutch Position Sensor Circuit High",
    "P0809": "Clutch Position Sensor Circuit Intermittent",
    "P0810": "Clutch Position Control Error",
    "P0811": "Excessive Clutch Slippage",
    "P0812": "Reverse Input Circuit",
    "P0813": "Reverse Output Circuit",
    "P0814": "Transmission Range Display Circuit",
    "P0815": "Upshift Switch Circuit",
    "P0816": "Downshift Switch Circuit",
    "P0817": "Starter Disable Circuit",
    "P0818": "Driveline Disconnect Switch Circuit",
    "P0819": "Up and Down Shift Switch to Transmission Range Correlation",
    "P0820": "Gear Lever X-Y Position Sensor Circuit",
    "P0821": "Gear Lever X Position Circuit",
    "P0822": "Gear Lever Y Position Circuit",
    "P0823": "Gear Lever X Position Circuit Intermittent",
    "P0824": "Gear Lever Y Position Circuit Intermittent",
    "P0825": "Gear Lever Push-Pull Switch (Shift Anticipate)",
    "P0826": "Up and Down Shift Switch Circuit",
    "P0827": "Up and Down Shift Switch Circuit Low",
    "P0828": "Up and Down Shift Switch Circuit High",
    "P0829": "5-6 Shift Malfunction",
    "P0830": "Clutch Pedal Switch A Circuit",
    "P0831": "Clutch Pedal Switch A Circuit Low",
    "P0832": "Clutch Pedal Switch A Circuit High",
    "P0833": "Clutch Pedal Switch B Circuit",
    "P0834": "Clutch Pedal Switch B Circuit Low",
    "P0835": "Clutch Pedal Switch B Circuit High",
    "P0836": "Four Wheel Drive (4WD) Switch Circuit",
    "P0837": "Four Wheel Drive (4WD) Switch Circuit Range/Performance",
    "P0838": "Four Wheel Drive (4WD) Switch Circuit Low",
    "P0839": "Four Wheel Drive (4WD) Switch Circuit High",
    "P0840": "Transmission Fluid Pressure Sensor/Switch A Circuit",
    "P0841": "Transmission Fluid Pressure Sensor/Switch A Circuit Range/Performance",
    "P0842": "Transmission Fluid Pressure Sensor/Switch A Circuit Low",
    "P0843": "Transmission Fluid Pressure Sensor/Switch A Circuit High",
    "P0844": "Transmission Fluid Pressure Sensor/Switch A Circuit Intermittent",
    "P0845": "Transmission Fluid Pressure Sensor/Switch B Circuit",
    "P0846": "Transmission Fluid Pressure Sensor/Switch B Circuit Range/Performance",
    "P0847": "Transmission Fluid Pressure Sensor/Switch B Circuit Low",
    "P0848": "Transmission Fluid Pressure Sensor/Switch B Circuit High",
    "P0849": "Transmission Fluid Pressure Sensor/Switch B Circuit Intermittent",
    "P0850": "Park/Neutral Switch Input Circuit",
    "P0851": "Park/Neutral Switch Input Circuit Low",
    "P0852": "Park/Neutral Switch Input Circuit High",
    "P0853": "Drive Switch Input Circuit",
    "P0854": "Drive Switch Input Circuit Low",
    "P0855": "Drive Switch Input Circuit High",
    "P0856": "Traction Control Input Signal",
    "P0857": "Traction Control Input Signal Range/Performance",
    "P0858": "Traction Control Input Signal Low",
    "P0859": "Traction Control Input Signal High",
    "P0860": "Gear Shift Module Communication Circuit",
    "P0861": "Gear Shift Module Communication Circuit Low",
    "P0862": "Gear Shift Module Communication Circuit High",
    "P0863": "TCM Communication Circuit",
    "P0864": "TCM Communication Circuit Range/Performance",
    "P0865": "TCM Communication Circuit Low",
    "P0866": "TCM Communication Circuit High",
    "P0867": "Transmission Fluid Pressure",
    "P0868": "Transmission Fluid Pressure Low",
    "P0869": "Transmission Fluid Pressure High",
    "P0870": "Transmission Fluid Pressure Sensor/Switch C Circuit",
    "P0871": "Transmission Fluid Pressure Sensor/Switch C Circuit Range/Performance",
    "P0872": "Transmission Fluid Pressure Sensor/Switch C Circuit Low",
    "P0873": "Transmission Fluid Pressure Sensor/Switch C Circuit High",
    "P0874": "Transmission Fluid Pressure Sensor/Switch C Circuit Intermittent",
    "P0875": "Transmission Fluid Pressure Sensor/Switch D Circuit",
    "P0876": "Transmission Fluid Pressure Sensor/Switch D Circuit Range/Performance",
    "P0877": "Transmission Fluid Pressure Sensor/Switch D Circuit Low",
    "P0878": "Transmission Fluid Pressure Sensor/Switch D Circuit High",
    "P0879": "Transmission Fluid Pressure Sensor/Switch D Circuit Intermittent",
    "P0880": "TCM Power Input Signal",
    "P0881": "TCM Power Input Signal Range/Performance",
    "P0882": "TCM Power Input Signal Low",
    "P0883": "TCM Power Input Signal High",
    "P0884": "TCM Power Input Signal Intermittent",
    "P0885": "TCM Power Relay Control Circuit/Open",
    "P0886": "TCM Power Relay Control Circuit Low",
    "P0887": "TCM Power Relay Control Circuit High",
    "P0888": "TCM Power Relay Sense Circuit",
    "P0889": "TCM Power Relay Sense Circuit Range/Performance",
    "P0890": "TCM Power Relay Sense Circuit Low",
    "P0891": "TCM Power Relay Sense Circuit High",
    "P0892": "TCM Power Relay Sense Circuit Intermittent",
    "P0893": "Multiple Gears Engaged",
    "P0894": "Transmission Component Slipping",
    "P0895": "Shift Time Too Short",
    "P0896": "Shift Time Too Long",
    "P0897": "Transmission Fluid Deteriorated",
    "P0898": "Transmission Control System MIL Request Circuit Low",
    "P0899": "Transmission Control System MIL Request Circuit High",

    # ---- P09xx: Transmission (continued) ----
    "P0900": "Clutch Actuator Circuit/Open",
    "P0901": "Clutch Actuator Circuit Range/Performance",
    "P0902": "Clutch Actuator Circuit Low",
    "P0903": "Clutch Actuator Circuit High",
    "P0904": "Gate Select Position Circuit",
    "P0905": "Gate Select Position Circuit Range/Performance",
    "P0906": "Gate Select Position Circuit Low",
    "P0907": "Gate Select Position Circuit High",
    "P0908": "Gate Select Position Circuit Intermittent",
    "P0909": "Gate Select Control Error",
    "P0910": "Gate Select Actuator Circuit/Open",
    "P0911": "Gate Select Actuator Circuit Range/Performance",
    "P0912": "Gate Select Actuator Circuit Low",
    "P0913": "Gate Select Actuator Circuit High",
    "P0914": "Gear Shift Position Circuit",
    "P0915": "Gear Shift Position Circuit Range/Performance",
    "P0916": "Gear Shift Position Circuit Low",
    "P0917": "Gear Shift Position Circuit High",
    "P0918": "Gear Shift Position Circuit Intermittent",
    "P0919": "Gear Shift Position Control Error",
    "P0920": "Gear Shift Forward Actuator Circuit/Open",
    "P0921": "Gear Shift Forward Actuator Circuit Range/Performance",
    "P0922": "Gear Shift Forward Actuator Circuit Low",
    "P0923": "Gear Shift Forward Actuator Circuit High",
    "P0924": "Gear Shift Reverse Actuator Circuit/Open",
    "P0925": "Gear Shift Reverse Actuator Circuit Range/Performance",
    "P0926": "Gear Shift Reverse Actuator Circuit Low",
    "P0927": "Gear Shift Reverse Actuator Circuit High",
    "P0928": "Gear Shift Lock Solenoid Control Circuit/Open",
    "P0929": "Gear Shift Lock Solenoid Control Circuit Range/Performance",
    "P0930": "Gear Shift Lock Solenoid Control Circuit Low",
    "P0931": "Gear Shift Lock Solenoid Control Circuit High",
    "P0932": "Hydraulic Pressure Sensor Circuit",
    "P0933": "Hydraulic Pressure Sensor Range/Performance",
    "P0934": "Hydraulic Pressure Sensor Circuit Low",
    "P0935": "Hydraulic Pressure Sensor Circuit High",
    "P0936": "Hydraulic Pressure Sensor Circuit Intermittent",
    "P0937": "Hydraulic Oil Temperature Sensor Circuit",
    "P0938": "Hydraulic Oil Temperature Sensor Range/Performance",
    "P0939": "Hydraulic Oil Temperature Sensor Circuit Low",
    "P0940": "Hydraulic Oil Temperature Sensor Circuit High",
    "P0941": "Hydraulic Oil Temperature Sensor Circuit Intermittent",
    "P0942": "Hydraulic Pressure Unit",
    "P0943": "Hydraulic Pressure Unit Cycling Period Too Short",
    "P0944": "Hydraulic Pressure Unit Loss of Pressure",
    "P0945": "Hydraulic Pump Relay Circuit/Open",
    "P0946": "Hydraulic Pump Relay Circuit Range/Performance",
    "P0947": "Hydraulic Pump Relay Circuit Low",
    "P0948": "Hydraulic Pump Relay Circuit High",
    "P0949": "Auto Shift Manual Adaptive Learning Not Complete",
    "P0950": "Auto Shift Manual Control Circuit",
    "P0951": "Auto Shift Manual Control Circuit Range/Performance",
    "P0952": "Auto Shift Manual Control Circuit Low",
    "P0953": "Auto Shift Manual Control Circuit High",
    "P0954": "Auto Shift Manual Control Circuit Intermittent",
    "P0955": "Auto Shift Manual Mode Circuit",
    "P0956": "Auto Shift Manual Mode Circuit Range/Performance",
    "P0957": "Auto Shift Manual Mode Circuit Low",
    "P0958": "Auto Shift Manual Mode Circuit High",
    "P0959": "Auto Shift Manual Mode Circuit Intermittent",
    "P0960": "Pressure Control Solenoid A Control Circuit/Open",
    "P0961": "Pressure Control Solenoid A Control Circuit Range/Performance",
    "P0962": "Pressure Control Solenoid A Control Circuit Low",
    "P0963": "Pressure Control Solenoid A Control Circuit High",
    "P0964": "Pressure Control Solenoid B Control Circuit/Open",
    "P0965": "Pressure Control Solenoid B Control Circuit Range/Performance",
    "P0966": "Pressure Control Solenoid B Control Circuit Low",
    "P0967": "Pressure Control Solenoid B Control Circuit High",
    "P0968": "Pressure Control Solenoid C Control Circuit/Open",
    "P0969": "Pressure Control Solenoid C Control Circuit Range/Performance",
    "P0970": "Pressure Control Solenoid C Control Circuit Low",
    "P0971": "Pressure Control Solenoid C Control Circuit High",
    "P0972": "Shift Solenoid A Control Circuit Range/Performance",
    "P0973": "Shift Solenoid A Control Circuit Low",
    "P0974": "Shift Solenoid A Control Circuit High",
    "P0975": "Shift Solenoid B Control Circuit Range/Performance",
    "P0976": "Shift Solenoid B Control Circuit Low",
    "P0977": "Shift Solenoid B Control Circuit High",
    "P0978": "Shift Solenoid C Control Circuit Range/Performance",
    "P0979": "Shift Solenoid C Control Circuit Low",
    "P0980": "Shift Solenoid C Control Circuit High",
    "P0981": "Shift Solenoid D Control Circuit Range/Performance",
    "P0982": "Shift Solenoid D Control Circuit Low",
    "P0983": "Shift Solenoid D Control Circuit High",
    "P0984": "Shift Solenoid E Control Circuit Range/Performance",
    "P0985": "Shift Solenoid E Control Circuit Low",
    "P0986": "Shift Solenoid E Control Circuit High",
    "P0987": "Transmission Fluid Pressure Sensor/Switch E Circuit",
    "P0988": "Transmission Fluid Pressure Sensor/Switch E Circuit Range/Performance",
    "P0989": "Transmission Fluid Pressure Sensor/Switch E Circuit Low",
    "P0990": "Transmission Fluid Pressure Sensor/Switch E Circuit High",
    "P0991": "Transmission Fluid Pressure Sensor/Switch E Circuit Intermittent",
    "P0992": "Transmission Fluid Pressure Sensor/Switch F Circuit",
    "P0993": "Transmission Fluid Pressure Sensor/Switch F Circuit Range/Performance",
    "P0994": "Transmission Fluid Pressure Sensor/Switch F Circuit Low",
    "P0995": "Transmission Fluid Pressure Sensor/Switch F Circuit High",
    "P0996": "Transmission Fluid Pressure Sensor/Switch F Circuit Intermittent",
    "P0997": "Shift Solenoid F Control Circuit Range/Performance",
    "P0998": "Shift Solenoid F Control Circuit Low",
    "P0999": "Shift Solenoid F Control Circuit High",

    # ---- P0Axx: Hybrid Propulsion ----
    "P0A00": "Motor Electronics Coolant Temperature Sensor Circuit",
    "P0A01": "Motor Electronics Coolant Temperature Sensor Circuit Range/Performance",
    "P0A02": "Motor Electronics Coolant Temperature Sensor Circuit Low",
    "P0A03": "Motor Electronics Coolant Temperature Sensor Circuit High",
    "P0A04": "Motor Electronics Coolant Temperature Sensor Circuit Intermittent",
    "P0A05": "Motor Electronics Coolant Pump Control Circuit/Open",
    "P0A06": "Motor Electronics Coolant Pump Control Circuit Low",
    "P0A07": "Motor Electronics Coolant Pump Control Circuit High",
    "P0A08": "DC/DC Converter Status Circuit",
    "P0A09": "DC/DC Converter Status Circuit Low Input",
    "P0A0A": "DC/DC Converter Status Circuit High Input",
    "P0A0B": "DC/DC Converter Status Circuit Range/Performance",
    "P0A0C": "High Voltage System Interlock Circuit",
    "P0A0D": "High Voltage System Interlock Circuit Range/Performance",
    "P0A0E": "High Voltage System Interlock Circuit Low",
    "P0A0F": "Engine Failed to Start",
    "P0A10": "Drive Motor A Inverter Power Module Hot",
    "P0A11": "DC/DC Converter Temperature Sensor A Circuit",
    "P0A12": "DC/DC Converter Temperature Sensor A Circuit Range/Performance",
    "P0A13": "DC/DC Converter Temperature Sensor A Circuit Low",
    "P0A14": "DC/DC Converter Temperature Sensor A Circuit High",
    "P0A15": "DC/DC Converter Temperature Sensor A Circuit Intermittent",
    "P0A16": "Drive Motor A Position Sensor Circuit",
    "P0A17": "Drive Motor A Position Sensor Circuit Range/Performance",
    "P0A18": "Drive Motor A Position Sensor Circuit Low",
    "P0A19": "Drive Motor A Position Sensor Circuit High",
    "P0A1A": "Generator Control Module",
    "P0A1B": "Drive Motor A Control Module",
    "P0A1C": "Drive Motor A Inverter Performance",
    "P0A1E": "Drive Motor B Control Module",
    "P0A1F": "Battery Energy Control Module",
    "P0A20": "Drive Motor A Current Sensor Circuit",
    "P0A21": "Drive Motor A Current Sensor Circuit Range/Performance",
    "P0A22": "Drive Motor A Current Sensor Circuit Low",
    "P0A23": "Drive Motor A Current Sensor Circuit High",
    "P0A24": "Drive Motor A Current Sensor Circuit Intermittent",
    "P0A25": "Drive Motor B Position Sensor Circuit",
    "P0A26": "Drive Motor B Position Sensor Circuit Range/Performance",
    "P0A27": "Drive Motor B Position Sensor Circuit Low",
    "P0A28": "Drive Motor B Position Sensor Circuit High",
    "P0A29": "Drive Motor B Position Sensor Circuit Intermittent",
    "P0A2A": "Drive Motor A Temperature Sensor Circuit",
    "P0A2B": "Drive Motor A Temperature Sensor Circuit Range/Performance",
    "P0A2C": "Drive Motor A Temperature Sensor Circuit Low",
    "P0A2D": "Drive Motor A Temperature Sensor Circuit High",
    "P0A2E": "Drive Motor A Temperature Sensor Circuit Intermittent",
    "P0A2F": "Drive Motor A Temperature Sensor Circuit Over Temperature",
    "P0A30": "Drive Motor B Current Sensor Circuit",
    "P0A31": "Drive Motor B Current Sensor Circuit Range/Performance",
    "P0A32": "Drive Motor B Current Sensor Circuit Low",
    "P0A33": "Drive Motor B Current Sensor Circuit High",
    "P0A34": "Drive Motor B Current Sensor Circuit Intermittent",
    "P0A35": "Drive Motor B Temperature Sensor Circuit",
    "P0A36": "Drive Motor B Temperature Sensor Circuit Range/Performance",
    "P0A37": "Drive Motor B Temperature Sensor Circuit Low",
    "P0A38": "Drive Motor B Temperature Sensor Circuit High",
    "P0A39": "Drive Motor B Temperature Sensor Circuit Intermittent",
    "P0A3A": "DC/DC Converter Temperature Sensor B Circuit",
    "P0A3B": "DC/DC Converter Temperature Sensor B Circuit Range/Performance",
    "P0A3C": "DC/DC Converter Temperature Sensor B Circuit Low",
    "P0A3D": "DC/DC Converter Temperature Sensor B Circuit High",
    "P0A3E": "DC/DC Converter Temperature Sensor B Circuit Intermittent",
    "P0A40": "Drive Motor A Position Sensor Performance",
    "P0A41": "Drive Motor A Position Sensor Stuck",
    "P0A42": "Drive Motor A Position Sensor Stuck Low",
    "P0A43": "Drive Motor A Position Sensor Stuck High",
    "P0A44": "Drive Motor A Position Sensor Circuit Intermittent",
    "P0A46": "Drive Motor B Position Sensor Performance",
    "P0A47": "Drive Motor B Position Sensor Stuck",
    "P0A48": "Drive Motor B Position Sensor Stuck Low",
    "P0A49": "Drive Motor B Position Sensor Stuck High",
    "P0A4A": "Drive Motor B Position Sensor Circuit Intermittent",
    "P0A50": "Generator Position Sensor Circuit",
    "P0A51": "Generator Position Sensor Circuit Range/Performance",
    "P0A52": "Generator Position Sensor Circuit Low",
    "P0A53": "Generator Position Sensor Circuit High",
    "P0A54": "Generator Position Sensor Circuit Intermittent",
    "P0A55": "Generator Current Sensor Circuit",
    "P0A56": "Generator Current Sensor Circuit Range/Performance",
    "P0A57": "Generator Current Sensor Circuit Low",
    "P0A58": "Generator Current Sensor Circuit High",
    "P0A59": "Generator Current Sensor Circuit Intermittent",
    "P0A5A": "Generator Temperature Sensor Circuit",
    "P0A5B": "Generator Temperature Sensor Circuit Range/Performance",
    "P0A5C": "Generator Temperature Sensor Circuit Low",
    "P0A5D": "Generator Temperature Sensor Circuit High",
    "P0A5E": "Generator Temperature Sensor Circuit Intermittent",
    "P0A60": "Generator Temperature Sensor Circuit Over Temperature",
    "P0A62": "Generator Position Sensor Performance",
    "P0A63": "Generator Position Sensor Stuck",
    "P0A64": "Generator Position Sensor Stuck Low",
    "P0A65": "Generator Position Sensor Stuck High",
    "P0A66": "Generator Position Sensor Circuit Intermittent",
    "P0A67": "Generator Inverter Module Over Temperature",
    "P0A6A": "Generator Failed to Start",
    "P0A6D": "Hybrid Battery Pack Sensor Module Circuit",
    "P0A6E": "Hybrid Battery Pack Sensor Module Circuit Range/Performance",
    "P0A6F": "Hybrid Battery Pack Sensor Module Circuit Intermittent",
    "P0A70": "Hybrid Battery Pack Air Temperature Sensor A Circuit",
    "P0A71": "Hybrid Battery Pack Air Temperature Sensor A Range/Performance",
    "P0A72": "Hybrid Battery Pack Air Temperature Sensor A Circuit Low",
    "P0A73": "Hybrid Battery Pack Air Temperature Sensor A Circuit High",
    "P0A74": "Hybrid Battery Pack Air Temperature Sensor A Circuit Intermittent",
    "P0A78": "Drive Motor A Inverter Performance",
    "P0A79": "Drive Motor B Inverter Performance",
    "P0A7A": "Generator Inverter Performance",
    "P0A7D": "Hybrid Battery Pack State of Charge Low",
    "P0A7E": "Hybrid Battery Pack Over Temperature",
    "P0A7F": "Hybrid Battery Pack Deterioration",
    "P0A80": "Replace Hybrid Battery Pack",
    "P0A81": "Hybrid Battery Pack Cooling Fan 1 Circuit",
    "P0A82": "Hybrid Battery Pack Cooling Fan 1 Circuit Range/Performance",
    "P0A83": "Hybrid Battery Pack Cooling Fan 1 Circuit Low",
    "P0A84": "Hybrid Battery Pack Cooling Fan 1 Circuit High",
    "P0A85": "Hybrid Battery Pack Cooling Fan 1 Circuit Intermittent",
    "P0A86": "Hybrid Battery Pack Cooling Fan 2 Circuit",
    "P0A87": "Hybrid Battery Pack Cooling Fan 2 Circuit Range/Performance",
    "P0A88": "Hybrid Battery Pack Cooling Fan 2 Circuit Low",
    "P0A89": "Hybrid Battery Pack Cooling Fan 2 Circuit High",
    "P0A8A": "Hybrid Battery Pack Cooling Fan 2 Circuit Intermittent",
    "P0A8B": "Hybrid Battery Pack Cooling Fan 3 Circuit",
    "P0A8C": "Hybrid Battery Pack Cooling Fan 3 Circuit Range/Performance",
    "P0A8D": "Hybrid Battery Pack Cooling Fan 3 Circuit Low",
    "P0A8E": "Hybrid Battery Pack Cooling Fan 3 Circuit High",
    "P0A8F": "Hybrid Battery Pack Cooling Fan 3 Circuit Intermittent",
    "P0A90": "Drive Motor A Performance",
    "P0A91": "Drive Motor B Performance",
    "P0A92": "Generator Performance",
    "P0A93": "Inverter A Cooling System Performance",
    "P0A94": "DC/DC Converter Performance",
    "P0A95": "High Voltage Fuse",
    "P0A96": "Hybrid Battery Pack State of Charge High",
    "P0A97": "Inverter B Cooling System Performance",
    "P0A98": "Drive Motor Cooling System Performance",
    "P0A99": "Hybrid Battery Pack Voltage Sensor Circuit",
    "P0A9A": "Hybrid Battery Pack Voltage Sensor Circuit Range/Performance",
    "P0A9B": "Hybrid Battery Pack Voltage Sensor Circuit Low",
    "P0A9C": "Hybrid Battery Pack Voltage Sensor Circuit High",
    "P0A9D": "Hybrid Battery Pack Temperature Sensor B Circuit",
    "P0A9E": "Hybrid Battery Pack Temperature Sensor B Circuit Range/Performance",
    "P0A9F": "Hybrid Battery Pack Temperature Sensor B Circuit Low",

    # ---- U0xxx: Network Communication ----
    "U0001": "High Speed CAN Communication Bus",
    "U0002": "High Speed CAN Communication Bus Performance",
    "U0003": "High Speed CAN Communication Bus (+) Open",
    "U0004": "High Speed CAN Communication Bus (+) Low",
    "U0005": "High Speed CAN Communication Bus (+) High",
    "U0006": "High Speed CAN Communication Bus (-) Open",
    "U0007": "High Speed CAN Communication Bus (-) Low",
    "U0008": "High Speed CAN Communication Bus (-) High",
    "U0009": "High Speed CAN Communication Bus (-) Shorted to Bus (+)",
    "U0010": "Medium Speed CAN Communication Bus",
    "U0011": "Medium Speed CAN Communication Bus Performance",
    "U0012": "Medium Speed CAN Communication Bus (+) Open",
    "U0013": "Medium Speed CAN Communication Bus (+) Low",
    "U0014": "Medium Speed CAN Communication Bus (+) High",
    "U0015": "Medium Speed CAN Communication Bus (-) Open",
    "U0016": "Medium Speed CAN Communication Bus (-) Low",
    "U0017": "Medium Speed CAN Communication Bus (-) High",
    "U0018": "Medium Speed CAN Communication Bus (-) Shorted to Bus (+)",
    "U0019": "Low Speed CAN Communication Bus",
    "U0020": "Low Speed CAN Communication Bus Performance",
    "U0021": "Low Speed CAN Communication Bus (+) Open",
    "U0022": "Low Speed CAN Communication Bus (+) Low",
    "U0023": "Low Speed CAN Communication Bus (+) High",
    "U0024": "Low Speed CAN Communication Bus (-) Open",
    "U0025": "Low Speed CAN Communication Bus (-) Low",
    "U0026": "Low Speed CAN Communication Bus (-) High",
    "U0027": "Low Speed CAN Communication Bus (-) Shorted to Bus (+)",
    "U0028": "Vehicle Communication Bus A",
    "U0029": "Vehicle Communication Bus A Performance",
    "U0030": "Vehicle Communication Bus A (+) Open",
    "U0031": "Vehicle Communication Bus A (+) Low",
    "U0032": "Vehicle Communication Bus A (+) High",
    "U0033": "Vehicle Communication Bus A (-) Open",
    "U0034": "Vehicle Communication Bus A (-) Low",
    "U0035": "Vehicle Communication Bus A (-) High",
    "U0036": "Vehicle Communication Bus A (-) Shorted to Bus A (+)",
    "U0037": "Vehicle Communication Bus B",
    "U0038": "Vehicle Communication Bus B Performance",
    "U0039": "Vehicle Communication Bus B (+) Open",
    "U0040": "Vehicle Communication Bus B (+) Low",
    "U0041": "Vehicle Communication Bus B (+) High",
    "U0042": "Vehicle Communication Bus B (-) Open",
    "U0043": "Vehicle Communication Bus B (-) Low",
    "U0044": "Vehicle Communication Bus B (-) High",
    "U0045": "Vehicle Communication Bus B (-) Shorted to Bus B (+)",
    "U0046": "Vehicle Communication Bus C",
    "U0047": "Vehicle Communication Bus C Performance",
    "U0048": "Vehicle Communication Bus C (+) Open",
    "U0049": "Vehicle Communication Bus C (+) Low",
    "U0050": "Vehicle Communication Bus C (+) High",
    "U0051": "Vehicle Communication Bus C (-) Open",
    "U0052": "Vehicle Communication Bus C (-) Low",
    "U0053": "Vehicle Communication Bus C (-) High",
    "U0054": "Vehicle Communication Bus C (-) Shorted to Bus C (+)",
    "U0055": "Vehicle Communication Bus D",
    "U0056": "Vehicle Communication Bus D Performance",
    "U0057": "Vehicle Communication Bus D (+) Open",
    "U0058": "Vehicle Communication Bus D (+) Low",
    "U0059": "Vehicle Communication Bus D (+) High",
    "U0060": "Vehicle Communication Bus D (-) Open",
    "U0061": "Vehicle Communication Bus D (-) Low",
    "U0062": "Vehicle Communication Bus D (-) High",
    "U0063": "Vehicle Communication Bus D (-) Shorted to Bus D (+)",
    "U0064": "Vehicle Communication Bus E",
    "U0065": "Vehicle Communication Bus E Performance",
    "U0066": "Vehicle Communication Bus E (+) Open",
    "U0067": "Vehicle Communication Bus E (+) Low",
    "U0068": "Vehicle Communication Bus E (+) High",
    "U0069": "Vehicle Communication Bus E (-) Open",
    "U0070": "Vehicle Communication Bus E (-) Low",
    "U0071": "Vehicle Communication Bus E (-) High",
    "U0072": "Vehicle Communication Bus E (-) Shorted to Bus E (+)",
    "U0073": "Control Module Communication Bus A Off",
    "U0074": "Control Module Communication Bus B Off",
    "U0075": "Control Module Communication Bus C Off",
    "U0076": "Control Module Communication Bus D Off",
    "U0077": "Control Module Communication Bus E Off",
    "U0100": "Lost Communication With ECM/PCM A",
    "U0101": "Lost Communication With TCM",
    "U0102": "Lost Communication With Transfer Case Control Module",
    "U0103": "Lost Communication With Gear Shift Module",
    "U0104": "Lost Communication With Cruise Control Module",
    "U0105": "Lost Communication With Fuel Injector Control Module",
    "U0106": "Lost Communication With Glow Plug Control Module",
    "U0107": "Lost Communication With Throttle Actuator Control Module",
    "U0108": "Lost Communication With Alternative Fuel Control Module",
    "U0109": "Lost Communication With Fuel Pump Control Module",
    "U0110": "Lost Communication With Drive Motor Control Module",
    "U0111": "Lost Communication With Battery Energy Control Module A",
    "U0112": "Lost Communication With Battery Energy Control Module B",
    "U0113": "Lost Communication With Emissions Critical Control Information",
    "U0114": "Lost Communication With Four-Wheel Drive Clutch Control Module",
    "U0115": "Lost Communication With ECM/PCM B",
    "U0116": "Lost Communication With Powertrain Control Module B",
    "U0117": "Lost Communication With Powertrain Control Module C",
    "U0118": "Lost Communication With Auxiliary Transmission Control Module",
    "U0119": "Lost Communication With Vehicle Dynamics Control Module",
    "U0120": "Lost Communication With Starter/Generator Control Module",
    "U0121": "Lost Communication With Anti-Lock Brake System (ABS) Control Module",
    "U0122": "Lost Communication With Vehicle Dynamics Control Module",
    "U0123": "Lost Communication With Yaw Rate Sensor Module",
    "U0124": "Lost Communication With Lateral Acceleration Sensor Module",
    "U0125": "Lost Communication With Multi-Axis Acceleration Sensor Module",
    "U0126": "Lost Communication With Steering Angle Sensor Module",
    "U0127": "Lost Communication With Tire Pressure Monitor Module",
    "U0128": "Lost Communication With Park Brake Control Module",
    "U0129": "Lost Communication With Brake System Control Module",
    "U0130": "Lost Communication With Steering Effort Control Module",
    "U0131": "Lost Communication With Power Steering Control Module",
    "U0132": "Lost Communication With Ride Level Control Module",
    "U0133": "Lost Communication With Restraints Occupant Classification System Module",
    "U0134": "Lost Communication With Vehicle Immobilizer Control Module",
    "U0135": "Lost Communication With Steering Column Control Module",
    "U0136": "Lost Communication With Four-Wheel Drive Control Module",
    "U0137": "Lost Communication With Trailer Brake Control Module",
    "U0138": "Lost Communication With All Wheel Drive (AWD) Control Module",
    "U0139": "Lost Communication With Suspension Control Module B",
    "U0140": "Lost Communication With Body Control Module",
    "U0141": "Lost Communication With Body Control Module A",
    "U0142": "Lost Communication With Body Control Module B",
    "U0143": "Lost Communication With Body Control Module C",
    "U0144": "Lost Communication With Body Control Module D",
    "U0145": "Lost Communication With Body Control Module E",
    "U0146": "Lost Communication With Gateway A",
    "U0147": "Lost Communication With Gateway B",
    "U0148": "Lost Communication With Gateway C",
    "U0149": "Lost Communication With Gateway D",
    "U0150": "Lost Communication With Gateway E",
    "U0151": "Lost Communication With Restraints Control Module",
    "U0152": "Lost Communication With Side Restraints Control Module Left",
    "U0153": "Lost Communication With Side Restraints Control Module Right",
    "U0154": "Lost Communication With Restraints Sensing Module Front",
    "U0155": "Lost Communication With Instrument Panel Cluster (IPC) Control Module",
    "U0156": "Lost Communication With Information Center A",
    "U0157": "Lost Communication With Information Center B",
    "U0158": "Lost Communication With Head Up Display",
    "U0159": "Lost Communication With Parking Assist Control Module",
    "U0160": "Lost Communication With Audible Alert Control Module",
    "U0161": "Lost Communication With Compass Module",
    "U0162": "Lost Communication With Navigation Display Module",
    "U0163": "Lost Communication With Navigation Control Module",
    "U0164": "Lost Communication With HVAC Control Module",
    "U0165": "Lost Communication With HVAC Control Module Rear",
    "U0166": "Lost Communication With Auxiliary Heater Control Module",
    "U0167": "Lost Communication With Vehicle Immobilizer Control Module",
    "U0168": "Lost Communication With Vehicle Security Control Module",
    "U0169": "Lost Communication With Sunroof Control Module",
    "U0170": "Lost Communication With Restraints System Sensor A",
    "U0171": "Lost Communication With Restraints System Sensor B",
    "U0172": "Lost Communication With Restraints System Sensor C",
    "U0173": "Lost Communication With Restraints System Sensor D",
    "U0174": "Lost Communication With Restraints System Sensor E",
    "U0175": "Lost Communication With Restraints System Sensor F",
    "U0176": "Lost Communication With Body Control Module B (Rear)",
    "U0177": "Lost Communication With Body Control Module C (Roof)",
    "U0178": "Lost Communication With Body Control Module D (Driver Door)",
    "U0179": "Lost Communication With Body Control Module E (Passenger Door)",
    "U0180": "Lost Communication With Automatic Lighting Control Module",
    "U0181": "Lost Communication With Headlamp Leveling Control Module",
    "U0182": "Lost Communication With Lighting Control Module Front",
    "U0183": "Lost Communication With Lighting Control Module Rear",
    "U0184": "Lost Communication With Radio",
    "U0185": "Lost Communication With Antenna Control Module",
    "U0186": "Lost Communication With Audio Amplifier",
    "U0187": "Lost Communication With Digital Disc Player/Changer Module A",
    "U0188": "Lost Communication With Digital Disc Player/Changer Module B",
    "U0189": "Lost Communication With Digital Disc Player/Changer Module C",
    "U0190": "Lost Communication With Digital Disc Player/Changer Module D",
    "U0191": "Lost Communication With Television",
    "U0192": "Lost Communication With Personal Computer",
    "U0193": "Lost Communication With Digital Audio Control Module A",
    "U0194": "Lost Communication With Digital Audio Control Module B",
    "U0195": "Lost Communication With Subscription Entertainment Receiver Module",
    "U0196": "Lost Communication With Rear Seat Entertainment Control Module",
    "U0197": "Lost Communication With Telephone Control Module",
    "U0198": "Lost Communication With Telematic Control Module",
    "U0199": "Lost Communication With Door Control Module A",
    "U0200": "Lost Communication With Door Control Module B",
    "U0201": "Lost Communication With Door Control Module C",
    "U0202": "Lost Communication With Door Control Module D",
    "U0203": "Lost Communication With Door Control Module E",
    "U0204": "Lost Communication With Door Control Module F",
    "U0205": "Lost Communication With Door Control Module G",
    "U0206": "Lost Communication With Folding Top Control Module",
    "U0207": "Lost Communication With Moveable Roof Control Module",
    "U0208": "Lost Communication With Seat Control Module A",
    "U0209": "Lost Communication With Seat Control Module B",
    "U0210": "Lost Communication With Seat Control Module C",
    "U0211": "Lost Communication With Seat Control Module D",
    "U0212": "Lost Communication With Steering Column Control Module",
    "U0213": "Lost Communication With Mirror Control Module",
    "U0214": "Lost Communication With Remote Function Actuation",
    "U0215": "Lost Communication With Door Switch A",
    "U0216": "Lost Communication With Door Switch B",
    "U0217": "Lost Communication With Door Switch C",
    "U0218": "Lost Communication With Door Switch D",
    "U0219": "Lost Communication With Door Switch E",
    "U0220": "Lost Communication With Door Switch F",
    "U0221": "Lost Communication With Door Switch G",
    "U0222": "Lost Communication With Door Window Motor A",
    "U0223": "Lost Communication With Door Window Motor B",
    "U0224": "Lost Communication With Door Window Motor C",
    "U0225": "Lost Communication With Door Window Motor D",
    "U0226": "Lost Communication With Door Window Motor E",
    "U0227": "Lost Communication With Door Window Motor F",
    "U0228": "Lost Communication With Door Window Motor G",
    "U0229": "Lost Communication With Heated Steering Wheel Module",
    "U0230": "Lost Communication With Rear Gate Module",
    "U0231": "Lost Communication With Rain Sensing Module",
    "U0232": "Lost Communication With Side Obstacle Detection Control Module Left",
    "U0233": "Lost Communication With Side Obstacle Detection Control Module Right",
    "U0234": "Lost Communication With Convenience Recall Module",
    "U0235": "Lost Communication With Cruise Control Front Distance Range Sensor",
    "U0300": "Internal Control Module Software Incompatibility",
    "U0301": "Software Incompatibility with ECM/PCM",
    "U0302": "Software Incompatibility with Transmission Control Module",
    "U0303": "Software Incompatibility with Transfer Case Control Module",
    "U0304": "Software Incompatibility with Gear Shift Control Module",
    "U0305": "Software Incompatibility with Cruise Control Module",
    "U0306": "Software Incompatibility with Fuel Injector Control Module",
    "U0307": "Software Incompatibility with Glow Plug Control Module",
    "U0308": "Software Incompatibility with Throttle Actuator Control Module",
    "U0309": "Software Incompatibility with Alternative Fuel Control Module",
    "U0310": "Software Incompatibility with Fuel Pump Control Module",
    "U0311": "Software Incompatibility with Drive Motor Control Module",
    "U0312": "Software Incompatibility with Battery Energy Control Module A",
    "U0313": "Software Incompatibility with Battery Energy Control Module B",
    "U0314": "Software Incompatibility with Vehicle Dynamics Control Module",
    "U0315": "Software Incompatibility with Anti-Lock Brake System Control Module",
    "U0316": "Software Incompatibility with Vehicle Dynamics Control Module",
    "U0317": "Software Incompatibility with Park Brake Control Module",
    "U0318": "Software Incompatibility with Brake System Control Module",
    "U0319": "Software Incompatibility with Steering Effort Control Module",
    "U0320": "Software Incompatibility with Power Steering Control Module",
    "U0321": "Software Incompatibility with Ride Level Control Module",
    "U0322": "Software Incompatibility with Body Control Module",
    "U0323": "Software Incompatibility with Instrument Panel Control Module",
    "U0324": "Software Incompatibility with HVAC Control Module",
    "U0325": "Software Incompatibility with Auxiliary Heater Control Module",
    "U0326": "Software Incompatibility with Vehicle Immobilizer Control Module",
    "U0327": "Software Incompatibility with Vehicle Security Control Module",
    "U0328": "Software Incompatibility with Steering Angle Sensor Module",
    "U0329": "Software Incompatibility with Steering Column Control Module",
    "U0330": "Software Incompatibility with Tire Pressure Monitor Module",
    "U0331": "Software Incompatibility with Body Control Module A",
    "U0400": "Invalid Data Received",
    "U0401": "Invalid Data Received From ECM/PCM",
    "U0402": "Invalid Data Received From Transmission Control Module",
    "U0403": "Invalid Data Received From Transfer Case Control Module",
    "U0404": "Invalid Data Received From Gear Shift Control Module",
    "U0405": "Invalid Data Received From Cruise Control Module",
    "U0406": "Invalid Data Received From Fuel Injector Control Module",
    "U0407": "Invalid Data Received From Glow Plug Control Module",
    "U0408": "Invalid Data Received From Throttle Actuator Control Module",
    "U0409": "Invalid Data Received From Alternative Fuel Control Module",
    "U0410": "Invalid Data Received From Fuel Pump Control Module",
    "U0411": "Invalid Data Received From Drive Motor Control Module",
    "U0412": "Invalid Data Received From Battery Energy Control Module A",
    "U0413": "Invalid Data Received From Battery Energy Control Module B",
    "U0414": "Invalid Data Received From Four-Wheel Drive Clutch Control Module",
    "U0415": "Invalid Data Received From Anti-Lock Brake System Control Module",
    "U0416": "Invalid Data Received From Vehicle Dynamics Control Module",
    "U0417": "Invalid Data Received From Park Brake Control Module",
    "U0418": "Invalid Data Received From Brake System Control Module",
    "U0419": "Invalid Data Received From Steering Effort Control Module",
    "U0420": "Invalid Data Received From Power Steering Control Module",
    "U0421": "Invalid Data Received From Ride Level Control Module",
    "U0422": "Invalid Data Received From Body Control Module",
    "U0423": "Invalid Data Received From Instrument Panel Control Module",
    "U0424": "Invalid Data Received From HVAC Control Module",
    "U0425": "Invalid Data Received From Auxiliary Heater Control Module",
    "U0426": "Invalid Data Received From Vehicle Immobilizer Control Module",
    "U0427": "Invalid Data Received From Vehicle Security Control Module",
    "U0428": "Invalid Data Received From Steering Angle Sensor Module",
    "U0429": "Invalid Data Received From Steering Column Control Module",
    "U0430": "Invalid Data Received From Tire Pressure Monitor Module",
    "U0431": "Invalid Data Received From Body Control Module A",
    "U1000": "Class 2 Communication Malfunction",
    "U1016": "Loss of Communication With PCM",
    "U1064": "Loss of Communication With BCM",
    "U1255": "Class 2 Communication Malfunction (Generic)",

    # ---- C0xxx: Chassis (Generic) ----
    "C0035": "Left Front Wheel Speed Sensor Circuit",
    "C0036": "Left Front Wheel Speed Sensor Circuit Range/Performance",
    "C0037": "Left Front Wheel Speed Sensor Circuit Low",
    "C0038": "Left Front Wheel Speed Sensor Circuit High",
    "C0040": "Right Front Wheel Speed Sensor Circuit",
    "C0041": "Right Front Wheel Speed Sensor Circuit Range/Performance",
    "C0042": "Right Front Wheel Speed Sensor Circuit Low",
    "C0043": "Right Front Wheel Speed Sensor Circuit High",
    "C0045": "Left Rear Wheel Speed Sensor Circuit",
    "C0046": "Left Rear Wheel Speed Sensor Circuit Range/Performance",
    "C0047": "Left Rear Wheel Speed Sensor Circuit Low",
    "C0048": "Left Rear Wheel Speed Sensor Circuit High",
    "C0050": "Right Rear Wheel Speed Sensor Circuit",
    "C0051": "Right Rear Wheel Speed Sensor Circuit Range/Performance",
    "C0052": "Right Rear Wheel Speed Sensor Circuit Low",
    "C0053": "Right Rear Wheel Speed Sensor Circuit High",
    "C0060": "Left Front ABS Solenoid 1 Circuit",
    "C0061": "Left Front ABS Solenoid 1 Circuit Range/Performance",
    "C0062": "Left Front ABS Solenoid 1 Circuit Low",
    "C0063": "Left Front ABS Solenoid 1 Circuit High",
    "C0065": "Left Front ABS Solenoid 2 Circuit",
    "C0066": "Left Front ABS Solenoid 2 Circuit Range/Performance",
    "C0067": "Left Front ABS Solenoid 2 Circuit Low",
    "C0068": "Left Front ABS Solenoid 2 Circuit High",
    "C0070": "Right Front ABS Solenoid 1 Circuit",
    "C0071": "Right Front ABS Solenoid 1 Circuit Range/Performance",
    "C0072": "Right Front ABS Solenoid 1 Circuit Low",
    "C0073": "Right Front ABS Solenoid 1 Circuit High",
    "C0075": "Right Front ABS Solenoid 2 Circuit",
    "C0076": "Right Front ABS Solenoid 2 Circuit Range/Performance",
    "C0077": "Right Front ABS Solenoid 2 Circuit Low",
    "C0078": "Right Front ABS Solenoid 2 Circuit High",
    "C0080": "Left Rear ABS Solenoid 1 Circuit",
    "C0081": "Left Rear ABS Solenoid 1 Circuit Range/Performance",
    "C0082": "Left Rear ABS Solenoid 1 Circuit Low",
    "C0083": "Left Rear ABS Solenoid 1 Circuit High",
    "C0085": "Left Rear ABS Solenoid 2 Circuit",
    "C0086": "Left Rear ABS Solenoid 2 Circuit Range/Performance",
    "C0087": "Left Rear ABS Solenoid 2 Circuit Low",
    "C0088": "Left Rear ABS Solenoid 2 Circuit High",
    "C0090": "Right Rear ABS Solenoid 1 Circuit",
    "C0091": "Right Rear ABS Solenoid 1 Circuit Range/Performance",
    "C0092": "Right Rear ABS Solenoid 1 Circuit Low",
    "C0093": "Right Rear ABS Solenoid 1 Circuit High",
    "C0095": "Right Rear ABS Solenoid 2 Circuit",
    "C0096": "Right Rear ABS Solenoid 2 Circuit Range/Performance",
    "C0097": "Right Rear ABS Solenoid 2 Circuit Low",
    "C0098": "Right Rear ABS Solenoid 2 Circuit High",
    "C0110": "ABS Pump Motor Circuit Malfunction",
    "C0121": "Valve Relay Circuit Malfunction",
    "C0128": "Low Brake Fluid Circuit/Open",
    "C0131": "ABS/TCS Control Valve Circuit Malfunction",
    "C0161": "ABS/TCS Brake Switch Circuit Malfunction",
    "C0186": "Lateral Accelerometer Sensor Circuit",
    "C0196": "Yaw Rate Sensor Circuit Malfunction",
    "C0200": "Wheel Speed Sensor Frequency Error",
    "C0201": "ABS Request Circuit Malfunction",
    "C0235": "Stop Lamp Switch Circuit",
    "C0241": "EBCM Control Valve Circuit",
    "C0265": "EBCM Motor Circuit/Open",
    "C0266": "EBCM Motor Circuit Performance",
    "C0267": "Pump Motor Circuit Open",
    "C0269": "Excessive Time to Center Steering",
    "C0273": "EBCM Relay Circuit Malfunction",
    "C0276": "Brake Pressure Sensor Circuit",
    "C0277": "Brake Pressure Sensor Circuit Performance",
    "C0287": "Deceleration Sensor Circuit Malfunction",
    "C0290": "Brake System Wiring Circuit Malfunction",
    "C0300": "Rear Speed Sensor Circuit Malfunction",
    "C0306": "Master Cylinder Pressure Sensor Circuit",
    "C0327": "Encoder Motor Circuit",
    "C0335": "Yaw Rate Sensor Bias Circuit",
    "C0371": "Malfunction Indicator Lamp (MIL) Circuit Malfunction",
    "C0387": "Loss of Battery Voltage",
    "C0455": "Steering Wheel Position Sensor Circuit",
    "C0460": "Steering Wheel Position Signal Circuit",
    "C0473": "Motor Control Processor Circuit",
    "C0550": "Electronic Control Unit (ECU) Malfunction",
    "C0561": "System Disabled Information Stored",
    "C0800": "Control Module Power Circuit Range/Performance",
    "C0896": "Electronic Control Unit Power Supply Out of Range",
    "C0899": "Device Power Voltage Low",
    "C0900": "Device Power Voltage High",

    # ---- B0xxx: Body (Generic) ----
    "B0001": "PCM Discrete Input Speed Signal Malfunction",
    "B0010": "Restraint System Driver Frontal Stage 1 Deployment Control",
    "B0011": "Restraint System Driver Frontal Stage 1 Deployment Control Performance",
    "B0012": "Restraint System Driver Frontal Stage 2 Deployment Control",
    "B0013": "Restraint System Driver Frontal Stage 2 Deployment Control Performance",
    "B0014": "Restraint System Driver Frontal Stage 3 Deployment Control",
    "B0015": "Restraint System Passenger Frontal Stage 1 Deployment Control",
    "B0016": "Restraint System Passenger Frontal Stage 1 Deployment Control Performance",
    "B0017": "Restraint System Passenger Frontal Stage 2 Deployment Control",
    "B0018": "Restraint System Passenger Frontal Stage 2 Deployment Control Performance",
    "B0020": "Restraint System Driver Side Deployment Control",
    "B0021": "Restraint System Driver Side Deployment Control Performance",
    "B0022": "Restraint System Driver Side Deployment Loop 2 Control",
    "B0024": "Restraint System Passenger Side Deployment Control",
    "B0025": "Restraint System Passenger Side Deployment Control Performance",
    "B0026": "Restraint System Passenger Side Deployment Loop 2 Control",
    "B0028": "Restraint System Right Side Deployment Control",
    "B0029": "Restraint System Right Side Deployment Control Performance",
    "B0040": "Restraint System Driver Pretensioner Deployment Control",
    "B0041": "Restraint System Driver Pretensioner Deployment Control Performance",
    "B0042": "Restraint System Passenger Pretensioner Deployment Control",
    "B0043": "Restraint System Passenger Pretensioner Deployment Control Performance",
    "B0050": "Restraint Driver Seatbelt Buckle Switch Circuit",
    "B0051": "Restraint Driver Seatbelt Buckle Switch Circuit Performance",
    "B0052": "Restraint Driver Seatbelt Buckle Switch Circuit Low",
    "B0053": "Restraint Driver Seatbelt Buckle Switch Circuit High",
    "B0055": "Restraint Passenger Seatbelt Buckle Switch Circuit",
    "B0056": "Restraint Passenger Seatbelt Buckle Switch Circuit Performance",
    "B0057": "Restraint Passenger Seatbelt Buckle Switch Circuit Low",
    "B0058": "Restraint Passenger Seatbelt Buckle Switch Circuit High",
    "B0061": "Side Restraints Sensor 1",
    "B0064": "Passenger Restraints Sensor 1",
    "B0070": "Frontal Crash Sensor (Driver)",
    "B0071": "Frontal Crash Sensor (Passenger)",
    "B0081": "Passenger Compartment Discriminating Sensor",
    "B0083": "Side Impact Sensor",
    "B0090": "Occupant Classification System Performance",
    "B0092": "Passenger Presence Sensor Circuit",
    "B0100": "Electronic Front End Sensor 1 Performance",
    "B0101": "Electronic Front End Sensor 1 Circuit",
    "B0102": "Electronic Front End Sensor 1 Circuit Low",
    "B0103": "Electronic Front End Sensor 1 Circuit High",
    "B0157": "Outside Air Temperature Sensor Circuit Low",
    "B0158": "Outside Air Temperature Sensor Circuit High",
    "B0159": "Outside Air Temperature Sensor Circuit Range/Performance",
    "B0160": "Inside Air Temperature Sensor Circuit Low",
    "B0161": "Inside Air Temperature Sensor Circuit High",
    "B0162": "Inside Air Temperature Sensor Circuit Range/Performance",
    "B0163": "In-Car Temperature Sensor Circuit",
    "B0164": "Evaporator Temperature Sensor Circuit",
    "B0168": "In-Car Temperature Sensor Circuit Range/Performance",
    "B0178": "Air Conditioner High Side Temperature Sensor Circuit",
    "B0183": "Sunload Sensor Circuit",
    "B0184": "Sunload Sensor Circuit Range/Performance",
    "B0200": "Climate Control Air Mix Door Actuator Circuit",
    "B0223": "Recirculation Door Actuator Circuit",
    "B0228": "Mode Door Actuator Circuit",
    "B0248": "Blower Motor Speed Control Circuit",
    "B0263": "HVAC Air Temperature Sensor Circuit",
    "B0408": "Temperature Control 1 (Bank 1) Circuit Malfunction",
    "B1000": "ECU Malfunction",
    "B1001": "Option Configuration Error",
    "B1325": "Device Power Circuit Low Voltage",
    "B1326": "Device Power Circuit High Voltage",
    "B1342": "ECU Defective",
    "B2900": "Door Lock Failure",
    "B2960": "Security Indicator Circuit Low",

    # ---- Common informational / no-fault codes ----
    "P1000": "OBD-II Monitor Testing Not Complete (Drive Cycle Incomplete)",
}

# total entries: 991
